### ISSUE TITLE
eda genomics: wgcna network : link to gene list: new tab if different website (maybe even if same site?)

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#1007]
one can't use the right click to open in a new tab..

<img width="1329" alt="Screenshot 2024-04-15 at 1 28 01 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/b697e43f-897b-40ce-8207-c0f5d93e9d86">

**Comment by dmfalke** [comment]
We are already opening eda in a new tab, so this would mean we are opening two new tabs, which doesn't seem ideal to me.

My proposal is that we do not open these things in new tabs, but use links, so that users can ctrl-click or right-click.
