### ISSUE TITLE
VDI. share doesnt work

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#1020]
<img width="1225" alt="Screenshot 2024-04-18 at 8 53 06 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/e4832c6e-03f9-438d-ae1b-2b2455993d2a">

**Comment by jernestmyers** [comment]
This appears to be a backend issue wherein the `user-id-query` response inadvertently changed.
