### ISSUE TITLE
BUG: standalone map legend colors should NOT change as the subset changes

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#1035]
on qa.restricted.clinepidb.org, using the PRISM Resistance surveillance study, the legend colors change as the filtered data changes.

If I filter "District" = Kanungu & Kabale and use donut markers to look at Plasmodium genotype / k13 Ala675Val, the legend looks like this:

<img width="246" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/532c16c5-988b-4187-b0f0-4cd1db79a941">

If I filter "District" = Lamwo and use donut markers to look at Plasmodium genotype / k13 Ala675Val, the legend looks like this:

<img width="253" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/3c0e8a86-3762-44f4-90f2-60fcdd26f996">

**Comment by dmfalke** [comment]
I think we are sorting by abundance, but should instead order by vocabulary order: https://github.com/VEuPathDB/web-monorepo/blob/f16f3e6d5bb7ca9a3e001148f4db4ca076ab3eea/packages/libs/eda/src/lib/map/analysis/utils/defaultOverlayConfig.ts#L178-L180

**Comment by bobular** [comment]
I think abundance order is what we want for the map, at least for high-cardinality variables. We just don't want that to change for low.

Oh, looky here: https://github.com/VEuPathDB/web-monorepo/issues/279
