### ISSUE TITLE
ClinEpi Study Access: in qa, providers cannot see other providers studies even if their studyAccess is public. 

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#1039]
Dave, I was wondering an easy way to do what Danica asks for.. is to assume that in qa  all public/protected/controlled studies are private.
Alternatively, to enable real study access qa before release,  have a new flag in presenters that specifies when a study is ready to be seen by other providers. For example: review_status: "under_review" and "ready"

**Comment by dmfalke** [comment]
I think it's risky to treat the same study access differently on qa and live. Why not make these studies "private", and hide "private" studies from the menu (if we aren't doing that already)?

**Comment by aurreco-uga** [comment]
sure that is what I had suggested in the slack thread originally.. set them private until ready for release.. 
but i would not hide them .. we do show them in menu even if private so users can request access.
