### ISSUE TITLE
Map - consider why we are not 'graying out' or dimming legend items that have no data in the current subset.

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#1059]
As per title. The `hasData` values are being passed correctly to the legend component, but `PlotListLegend` only has logic for disabling checkboxes, not greying out actual items.  Does anyone remember the history of this?

We don't want the greying out to be per viewport (or even per timeslider slice) because this would be too annoying for the user to see the legend reloading all the time.

**Comment by moontrip** [comment]
@bobular I think this is due to https://github.com/VEuPathDB/web-eda/issues/1602

**Comment by bobular** [comment]
Thank you for digging up the relevant history @moontrip 

I wonder if the map needs a different approach, because it has no checkboxes in the legend?

I'll leave this open but it can be very low priority!

**Comment by bobular** [comment]
The map's legend is subset-sensitive so there will never be items in the legend that are not in the subset.

If we wanted things greyed out in the legend that were not in the current **viewport**, we could do that, but we would want to avoid the spinner over an empty legend panel, because this breaks "continuity" which is important for the legend.

However, I will close this as "not fixing" for now.
