### ISSUE TITLE
Map: Refactor: Introduce MapType front end plugin

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#106]
In the future, we will have non-marker map types. When that time comes, we will want to move marker-based logic out of `MapAnalysisImpl`, since not all map types will have markers.

Instead, we should introduce a `MapType` plugin:

- Each `MapType` defines a plugin to render a "config panel" and a "map type layer"
- The "config panel" is what appears in the left-hand menu
- The "map type layer" is rendered on top of the map, and includes markers, legend, floater, etc
- The MapAnalysis component will simply render a <ActiveMapTypeLayer {...activeMapTypeConfig}/>, replacing all of the existing marker and legend logic
- It's likely that all of the marker-based map types will share a `MarkerMapTypeLayer` component

**Comment by d-callan** [comment]
to add a bit more detail to this, bubbles will have two parts to their legend. the first will indicate size and likely be a set of concentric circles, the second will indicate color and at least for whats been discussed so far will require a gradient legend.

**Comment by d-callan** [comment]
see https://github.com/VEuPathDB/web-monorepo/issues/249

**Comment by dmfalke** [comment]
I propose we introduce `MapTypePlugin`, which will include a component to render the configuration panel, and a component to render a "map layer" (which will include a legend, markers, floating vizs, etc).

This approach will make it possible to have non-marker map types (such as animation, time-based view, etc).

The map itself would continue to be rendered independently.


@bobular I would love you feedback on this proposal.

**Comment by dmfalke** [comment]
I'm going to rename this issue and move it back to "TODO". I also don't think it's needed for NIAID QO

**Comment by d-callan** [comment]
Just thinking if we want to be really flexible and future proof, then rendering the base map itself might be the purview of the 'map type'.

**Comment by dmfalke** [comment]
> Just thinking if we want to be really flexible and future proof, then rendering the base map itself might be the purview of the 'map type'. 

I had a similar thought. I'm not opposed to that. Can you think of use cases? Maybe if a map type wants to use a different base layer?

**Comment by d-callan** [comment]
I was thinking of choropleth and cartograms, etc

**Comment by dmfalke** [comment]
Cool, makes sense. I'm going to leave this here for future reference: https://leafletjs.com/examples/choropleth/

**Comment by bobular** [comment]
Even though this isn't urgent any more I like the idea of future proofing. Dave's proposal looks good!

Choropleths still go on top of a regular map, so I don't think the base layers need to be part of the plugin scheme.

**Comment by dmfalke** [comment]
Closed by #399
