### ISSUE TITLE
Address scrollbar rendering bugs

### ISSUE THREAD

**Issue by adnauseum** [VEuPathDB/web-monorepo#108]
Reopened after https://github.com/VEuPathDB/web-monorepo/pull/87 was accidentally merged - still need to address extra unwanted scrollbars - see screenshot in first comment.

This has been done already in the first incarnation:
<s>Please also add a horizontal scrollbar to the entity diagram in SAM (now in the filter menu item)

There is already horizontal scroll in the EDA so this should be simple?</s>

**Comment by adnauseum** [comment]
Example from Windows: 

![Image](https://user-images.githubusercontent.com/24446573/234092366-0168bcd5-09af-4248-93ee-eeb293e387a9.png)

**Comment by dmfalke** [comment]
I'm fairly certain that there are several `overflow: scroll` styling rules that should change to `overflow: auto`, and that will likely address the issue.

**Comment by dmfalke** [comment]
I did not mean to close this!

**Comment by bobular** [comment]
Reopening and editing to re-focus on just the unwanted scrollbars

**Comment by dmfalke** [comment]
@bobular This appears to be fixed. Can you double check and close if it is?

**Comment by dmfalke** [comment]
I'm pretty sure this has all been addressed
