### ISSUE TITLE
EDA - Featured variables styling

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#1094]
From David Roos:

> Might be easier to visually parse Featured Variables if entity is in a separate tab, or highlighted in bold (see mockups for LLINEUP2). Option 1 would be easier to read, and also (presumably) very easy to implement. Option 2 takes more vertical space. Option 3 takes more horizontal space. Option 4 would probably be harder to implement properly
>
> ![image](https://github.com/VEuPathDB/web-monorepo/assets/365139/e22b97bb-0b3c-4f2a-95b2-548789a75a62)

**Comment by bobular** [comment]
Proposal 2 agreed with five votes at a UX meeting as reported by @aurreco-uga
