### ISSUE TITLE
EDA User Dataset: Error thrown when installation is queued

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#1136]
See this screenshot:
![image](https://github.com/user-attachments/assets/ac7794ce-d8ac-4cc0-8d98-82a4f4de2966)

**Comment by dmfalke** [comment]
This is a regression due to a new feature added to `usePromise`, which causes errors to be thrown (`throwError: true`). When this option is set to `true`, the error is being thrown in the Promise's rejection callback. This causes the error to be thrown in an asynchronous context. The expected semantics of `throwError` is that the error is thrown synchronously, so that callers of the hook can catch the error.

**Comment by bobular** [comment]
Hi @dmfalke
According to https://github.com/VEuPathDB/ClinEpiWebsite/commit/9b94e5842d66495ea1dd1d6adb0816f8353097fb
and https://github.com/VEuPathDB/web-monorepo/compare/v1.0.153-patch.4...v1.0.153-patch.5
this fix should have gone to qa.clinepidb.org (q2 was rebuilt on 19 July - 3 days after the patch.5 release)

However I'm still seeing the error when I upload a new UD to qa.clinepidb.org :cry:

**Comment by dmfalke** [comment]
Qa sites are using the latest release, which was made before this fix. I just made a new release so it should be on qa sites tomorrow. Sorry for the confusion!

**Comment by bobular** [comment]
Ah, thanks. So the qa site isn't on [api-build-68](https://github.com/VEuPathDB/ClinEpiWebsite/compare/api-build-68) ?

How do we know which branch of XyzWebsite a site is on?
