### ISSUE TITLE
ClinEpi's pass-through new visualization icons should not include "Map markers" - also consider dropping "Coming soon!" entries

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#1142]
The regular map visualization (not the full-screen app) uses two backend plugins: `map-markers` and `map-markers-overlay`. The problem is that the `map-markers-overlay` is getting a viz icon:

![image](https://github.com/user-attachments/assets/61bc984c-5f44-437e-ab94-c8d6a95940e8)

The `apps` endpoint returns all the computes and their visualizations. The `pass` compute response lists `map-markers` and `map-markers-overlay`.

The front end, in single-app ClinEpi mode, renders the viz icons with [NewVisualizationPicker](https://github.com/VEuPathDB/web-monorepo/blob/main/packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx#L315) 

Note that Mbio and the full screen map use a similar component unhelpfully named `StartPage` ([here](https://github.com/VEuPathDB/web-monorepo/blob/main/packages/libs/eda/src/lib/core/components/computations/StartPage.tsx))

Both components iterate through the list of visualizations from the `apps` endpoint. The icon is greyed out if the front end does not have a plugin to deal with it. See here https://github.com/VEuPathDB/web-monorepo/blob/c803fc5b457fb85483c17e6418d8cd46400827b5/packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx#L351-L354

Given that we probably want to get rid of the "Coming soon" icons, the easiest fix is likely to replace the `orderBy` here: 

https://github.com/VEuPathDB/web-monorepo/blob/c803fc5b457fb85483c17e6418d8cd46400827b5/packages/libs/eda/src/lib/core/components/visualizations/VisualizationsContainer.tsx#L345-L348

with a filter.  There's no need to fix `StartPage` because it isn't used to render the `pass` viz plugins.

It's not clear how long this has been a bug. The front end code hasn't changed recently, and I'm pretty sure the `apps` response hasn't either. Maybe we just didn't notice it.

**Comment by dmfalke** [comment]
Do we need `map-markers-overlay` to be in the pass app? If not, we can remove it (and others we don't want to see) from here: https://github.com/VEuPathDB/service-eda/blob/c07805d16b55c5419124881c129e51c2a9fe3219/src/main/java/org/veupathdb/service/eda/data/metadata/AppsMetadata.java#L102-L115

**Comment by bobular** [comment]
As I said on Slack, the front end needs `map-markers-overlay` by the back door. It's used as a secondary endpoint for the regular EDA map viz. However, it shouldn't have its own icon in the new viz picker.
