### ISSUE TITLE
Networks: set cursor over label to pointer - third time's a charm

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#1165]
Seen on qa in both the network and bipartite networks.
A small thing, but when we mouse over the node label the cursor is not becoming a pointer. This is odd to me because a quick look through the code says it's set as a pointer in two places. So why it the mouse becoming a text selector instead?

It's a mystery to me!

**Comment by moontrip** [comment]
@asizemore I will take a look at it 🤞
