### ISSUE TITLE
Map: timeslider arrows layout with short variable name

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#1180]
My UD has a short "date" variable name

![image](https://github.com/user-attachments/assets/ab19470c-fbe5-44ea-96b3-fb8f0e4b1e62)

Needs to be

![image](https://github.com/user-attachments/assets/874e56e3-9458-4000-9f8d-4d889df10c99)

add `margin-left/right: auto` to div containing the date range selector

**Comment by bobular** [comment]
Maybe the arrows should be snug with the date picker inputs.

The arrows can have `margin-left: auto` and `margin-right: auto` respectively.

**Comment by moontrip** [comment]
This is resolved by https://github.com/VEuPathDB/web-monorepo/pull/1185 so closed
