### ISSUE TITLE
EDA: Add retry logic when re-reunning an expired job

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#1211]
This is related to compute jobs in eda. When a compute job is expired, and a request is made to rerun the job. A minio race condition causes a non ok response to be returned.

The idea is to have the client catch that response and try again, hoping the backend issue is resolved.

There is a utility function called fetchWithRetry somewhere in our code base 🙂.

**Comment by aurreco-uga** [comment]
compute platform bandaid to have 500 to stop on expired workspaces

https://github.com/VEuPathDB/lib-compute-platform/commit/252dd6de740ab3948b64f51f2c00a485e71bd090
