### ISSUE TITLE
OrthoMCL - protein mapping with diamond updates

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#1213]
- [x] Allow all file types
- [ ] Update verbiage on results page
- [x] Remove revise link
- [x] Make it clear that you can drag and drop
- [x] regarding expired diamond jobs, remove the link to the results, and the "rerun" link. de-emphasize row

**Comment by bobular** [comment]
What's the verbiage update?  I have removed the "BLAST" from "submit another job". Anything else?
