### ISSUE TITLE
eda: wgcna dataset: correlation viz: input data options missing

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#1223]
This is not the wgcna viz but the Correlation one. Should it work? Should it be removed?

<img width="1324" alt="Screenshot 2024-10-09 at 10 00 17 AM" src="https://github.com/user-attachments/assets/e6cb3109-6ca4-44ac-baf2-a2671caa952a">

**Comment by asizemore** [comment]
Self-correlation has been turned off for genomics. The visualization option no longer appears in the list of options on the plasmo qa site. 
See https://github.com/VEuPathDB/service-eda/pull/68
