### ISSUE TITLE
Header and menu styling and layout (map viewport change)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#125]
From https://veupathdb.atlassian.net/wiki/spaces/WG/pages/255033345/2023-04-24+Map+UX 

### Menu

- [ ] Make the line separating menu items from configuration panels darker / thicker to indicate that the 2 configuration panels are connected to each other

- [x] Close drawer buttons
  - Button to close menu drawer is too small → make bigger 
  - Now that header will no longer be close-able, the button to close the menu drawer can be repositioned → move to the top right of the open menu panel

### Header

- [x] Header should remain open; remove the button to collapse the header - already in this issue --> https://github.com/VEuPathDB/web-monorepo/issues/107 

  - The header contains essential information
  - **The header should NOT hide points in the viewport (going forward, exclude points under the header from the viewport)** 

- [x]  Header can blend into the url bar depending on browser configs 

  - Try using a very light “theme” color (ie, light sage for VectorBase)
  -  Alternatively, try using color borders around the header and menu and keeping the white
  - Do not use transparency as markers under the header will be excluded from the viewport

@asizemore has made [mockups](https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?node-id=716%3A17097&t=L0y5pbzD8Hd3qTQ1-1)  - not sure what the consensus is!

**Comment by asizemore** [comment]
I think people generally liked the light background best. We don't have mockups for a larger tab explicitly, though there were some discussions and ideas in the mockups (some are [here](https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?type=design&node-id=283-1128&t=KiRVokzHji2nFdD5-0), and others scattered around in there). If you'd like something in particular let me know!

**Comment by jernestmyers** [comment]
**Note**: there is [a separate issue to maintain visibility of the map header](https://github.com/VEuPathDB/web-monorepo/issues/107).

Additionally, as stated [in the PR](https://github.com/VEuPathDB/web-monorepo/pull/127):
> Also related to https://github.com/VEuPathDB/web-monorepo/issues/125. Note that this does not address the issue of hiding data beneath the header.
