### ISSUE TITLE
Map: Timeline + marginal histogram floating visualization

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#131]
This is needed for the tick QO, deadline sept.

This ticket is to build a floating visualization for the standalone map, using the component built in #130. The line and histo should share xaxis controls and the xaxis should be identical for both. This means the xaxis of the lineplot MUST be binned, where a typical line plot would have the option. 

The backend strategy, as of now, is to continue to use the two existing endpoint for line and histo separately. if necessary, a backend ticket will be filed to ensure consistent bins. Given that  a) the existing histogram supports semantic zooming and the line plot doesnt and  b) this histogram being marginal means it will only represent counts for non-NULL values of the line plot's yaxis variable.. I think the best strategy for requesting data would be to build the line plot request as usual, and from the response parse the default bin width. Then make a second request to histogram using that bin width, while also adding a filter for all values (non-NULLs) of the yaxis variable of the line plot. I suppose though if the lineplot yaxis already has been filtered on by the user, then no need to add the filter though.

If any of that ^ is unclear or we dont think will work for some reason, let me know.

EDIT: after reading the above back, I'd like to clarify the histo request. It should take the existing filters on the yaxis variable of the line plot and add to them wherever necessary to exclude values which were also excluded from the denominator. And it should use both the bin width and viewport the line plot used.

**Comment by bobular** [comment]
Makes sense to me :+1: 

So this would be a new visualisation type (from the client/user perspective)?

I think that's probably a good idea. The alternative is to have the marginal plot optional and only an option when binning is on for continuous/date vars. I think that's probably more cognitive overload than having a new plot type.

**Comment by d-callan** [comment]
Agree. I intentionally didn't make a ticket to add the marginal histo to the existing line plot viz, for some of the reasons you list.

**Comment by d-callan** [comment]
outside of binning being required i think the specs for this are the same as the floating lineplot. in particular, the variable inputs are the same.
