### ISSUE TITLE
Filter-aware variable constraints in visualizations

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#138]
I believe this only affects categorical variables, which can change from high-cardinality to low-cardinality upon filtering down to <=8 values.

When a variable has been filtered down to <=8 values, it should appear as clickable in the overlay variable selector, for example.  Similarly a variable filtered down to <=10 values should be allowed as an x-axis variable for bar or boxplot.

Implementation hint: we probably need to pass `filters` to `InputVariables` and either
1. make a modified version of `entities` (the study metadata) where each variable's `distinctValuesCount` is set from the number of filter values for that variable (if filtering on it, and if it's categorical), and pass this to `filterConstraints` 
2. modify `filterConstraints` to alter `variable.distinctValuesCount` based on filter values when appropriate.

Hope that makes sense. Both are probably equivalent efficiency-wise.

**Comment by d-callan** [comment]
happy this is done, but wondering if we should have done https://github.com/VEuPathDB/web-eda/issues/1698 first?
