### ISSUE TITLE
Standalone map: map state/analyses management panel

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#140]
This is effectively a small "My Analyses" panel but it has some slightly different functionality.

It's a list of saved analyses for the current study (and no way to switch to other studies, study name should not be displayed).

Above the list is the editable name of the current analysis, and a "new analysis" button.

Clicking on an item in the list will switch to that saved analysis.
The list could also have delete buttons.

The "do you want to rename?" existing EDA functionality would be good to have on the "new analysis" button, but not essential right now. Make a new ticket if it's not trivial to do.

**Comment by dmfalke** [comment]
Related to #89
