### ISSUE TITLE
Default zoom level should be zero, not 4

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#176]
Ideally, all data for a study or megastudy should appear in the user's initial viewport, no matter how big their screen is.

This is because the default behaviour of the map is to "fly to" the best-fit view of the marker data shown in the initial default viewport.

For some reason the default is 4, but zero should work better.

**Comment by moontrip** [comment]
@bobular Actually I already changed it to 2 at the custom zoom control PR https://github.com/VEuPathDB/web-monorepo/pull/137. Do you think it should be zero, not 2 that is used for MapViz?

**Comment by bobular** [comment]
Already done.

Actually 1, not zero, but all good.
