### ISSUE TITLE
Map: Update 'Markers' menu entry to allow more advanced user configuration

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#190]
Additional tweaks from [2023-06-15 Map UX meeting](https://veupathdb.atlassian.net/wiki/spaces/WG/pages/300613633/2023-06-15+Map+UX):

- [x] try to use the same layout as regular visualizations for the marker config panel:
      - variable picker at top
         - can we give this a `max-width`?
         - not discussed at meeting, but if it's at the very top, does it really need a "Color:" heading? (For continuous vars, is the color gradient really a color? maybe)
      - plot next (in this case it's the marker preview)
      - controls
      - value picker distributions (checkbox table or histogram)
- [x] Heading for preview is now "Summary marker (all filtered data)" (plus possible tooltip to explain that it's visible plus any other filtered data outside the viewport?)
- [x] Controls subheadings
      - chart marker: Marker X-axis controls (continuous only: contains "binning method"), Marker Y-axis controls (contains: count/proportion radio button and logscale toggle).  The extra "Marker" in the headings might be overkill but let's see it first. 
      - donut marker: Doesn't have an X-axis. We just need to have a binning method selector for continuous variables. Do we just use a "Donut controls" heading? Bit of a grey area...
- [x] Binning method selector implementation notes:  the `ContinousVariableMetadataResponse` contains three types of binRanges: `equalInterval`, `quantile` (actually decile) and `standardDeviation`.  We are currently hardcoded to use `equalInterval` somewhere. Should be simple to use the other two types based on the radio button-controlled state.
- [x] For categorical variables, put a box around the checkbox table (and add a scroll bar) - see [figma](https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?type=design&node-id=1026%3A40876&t=qHZatybYd01dHdXe-1) - color up to you!
- [x] We didn't decide on a search box in the checkbox table - exclude for now.
- [x] Add a radio button control inside the box under the table, "Show counts for :white_circle: filtered :black_circle: visible" (categorical only)
- [x] I'm 95% sure we decided this radio button will NOT affect the summary marker (that's why we put the box around the table)
- [x] #313
- [x] Continuous reference distribution
      - try labelling it "Raw distribution of <Variable name> over all filtered data" (tooltip could mention "equal-binned" ??)
      - color uniform #333 (add this to HistogramProps: `colorPalette: Array(8).fill('#333')`)
      - reduce margins (`spacingOptions` should hopefully do it)

More categorical tweaks

- [ ] debounce with 2s delay
- [x] confirmation of previous plans to deal with >7 selections
      - allow any number of checkbox selections
      - but only use the last valid combination of checkboxes for the overlayConfig
      - _overlay_ a warning banner on top of the Summary marker (aka preview marker) to say "maximum 7 selections allowed, please deselect X values" (summary marker should always be visible, hence the scroll bar for the checkbox table) 
- [x] investigate issue with summary marker containing stale data after filters have been changed (Bob can demo)

General menu-related
- [x] implement the decision of this thread https://epvb.slack.com/archives/CMQ8K9XRS/p1686863706963029 ("Map Type" menu verbiage)

mockups exist in [figma](https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?type=design&node-id=0-1&t=oTp9KkfnBRYMg6CP-0).. ex screenshots as well

categorical
![image](https://github.com/VEuPathDB/web-monorepo/assets/53306535/3309e0eb-21e9-4572-ae4e-4e6a74d4b394)

continuous
![image](https://github.com/VEuPathDB/web-monorepo/assets/53306535/f1f10c5e-6455-47ca-a244-d0824ff41a7c)

**NOTE:** I believe some changes were discussed after these mockups were made, but idk if the mockups were updated to reflect them. For ex, The histogram shown when configuring a continuous variable will always reflect the subset, rather than offering the visible vs filtered toggle.

@asizemore @bobular do you know of any other changes discussed which are important to note here?

**Comment by bobular** [comment]
Some implementation thoughts for the "Choose values" sorted checkbox list component:

Assume #143 is merged or branching from it!

`PieMarkerConfigurationMenu` and `BarPlotMarkerConfigurationMenu` need to display the new component when `overlayConfig.overlayType === 'categorical'`

`overlayConfig.overlayValues` will already* contain the values that should have their checkboxes checked.

(* the `updateOverlayConfig` `useEffect` sets this via an async function when the overlay variable or filters change.  @dmfalke is going to cull some of our useEffects though...)

However the checkbox table thing needs the full list of values. You can get these from `subsettingClient.getDistribution()` which you can see used in `getMostFrequentValues()` in defaultOverlayConfig.ts.  I think we will pass the current `filters` to that request, but that's a detail that can be ironed out later, as is the viewport/whole_world radio button (which requires an extra viewport filter to be sent to the back end).

Are we OK having two different bits of code calling `subsettingClient.getDistribution()` or do we need to make `getMostFrequentValues` a bit more general purpose? Decisions decisions...

Anyway, checking the checkboxes should update the `overlayConfig` (changing its `overlayValues`) and everything else should just fall into place...!

**Comment by dmfalke** [comment]
> Are we OK having two different bits of code calling `subsettingClient.getDistribution()` or do we need to make `getMostFrequentValues` a bit more general purpose? Decisions decisions...

Unless I'm mistaken, both uses are in relation to the overlay variable of the marker. It might make sense to pull that call out to a separate variable that gets returned by the marker hook.

**Comment by bobular** [comment]
I'm not sure I understand. 

Also should we use the `<Mesa>` checkbox/table component for now? I know we came to that decision already but it might take Sam three days to figure out how to use it.

**Comment by asizemore** [comment]
A few updates to the mockups that were discussed but are no where represented:
- checkboxes will always be active. If a user interacts with them they get the Apply/Cancel buttons
- Use subtitle of the section possibly to save the space for the appearing Apply/Cancel buttons

Let me know if it would be helpful to have these or other changes in mockup form!

**Comment by bobular** [comment]
> Unless I'm mistaken, both uses are in relation to the overlay variable of the marker. It might make sense to pull that call out to a separate variable that gets returned by the marker hook.

Ah, I think I understand. When the original call is made to `getDefaultOverlayConfig` we should also return the full list of overlay values and their counts.  It's not currently a hook, but probably could be. Let's see how things look when Dave has exorcised the effects.

**Comment by dmfalke** [comment]
> > Unless I'm mistaken, both uses are in relation to the overlay variable of the marker. It might make sense to pull that call out to a separate variable that gets returned by the marker hook.
> 
> Ah, I think I understand. When the original call is made to `getDefaultOverlayConfig` we should also return the full list of overlay values and their counts, so we can re-use them in the new UI. It's not currently a hook, but probably could be. Let's see how things look when Dave has exorcised the effects.

Sorry for the delayed response. Yes, the basic idea is that we get the distribution once, and pass them to the config menu and the legend, one way or another. I haven't thought about the specifics of how we would do it. There may be some challenges.

**Comment by dmfalke** [comment]
Regarding debouncing, I suggest we wait and see if it's really needed. My theory is that most users will not be able to click more than one item within a reasonable debounce window.

If that proves to be wrong, there is a very nice implementation of a react-friendly `debounce` hiding in https://github.com/VEuPathDB/web-monorepo/blob/83035c01b9bd75371939c0027fe2e0e6029f4bbe/packages/libs/web-common/src/components/SiteSearch/TypeAheadInput.tsx#L148-L186
