### ISSUE TITLE
SAM: Add link to "My interactive maps" under "Workspace"

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#212]
### Description

There are two parts to this issue:
1. Update the routes
2. Update the menu items

### Update the routes

- [ ] Replace `/maps` with `/workspace/maps`
- [ ] Add a redirect from `/maps` to `/workspace/maps` for backward compatibility
- [ ] Update `packages/libs/eda/src/lib/map/MapVeuContainer.tsx` to render `AllAnalyses`, instead of `StudyList`.

### Update the menu items

_This only applies to genomics-site_

- [ ] Update the existing map links to use `/workspace/maps`
- [ ] Add a link to **My interactive maps** under the **Workspace** menu heading

**Comment by bobular** [comment]
I was just looking at some recently merged PRs and saw a `/maps` link in the following:

https://github.com/VEuPathDB/web-monorepo/blob/edbf0bcb67a9644ae18b6faf05519001d3196a23/packages/sites/genomics-site/webapp/wdkCustomization/js/client/components/homepage/VEuPathDBHomePage.tsx

The redirect will take care of it, but should we update it?
