### ISSUE TITLE
Make the map legend draggable

### ISSUE THREAD

**Issue by adnauseum** [VEuPathDB/web-monorepo#216]
# Some interactions we'd should decide upon.

- [x] When the side navigation opens, it will cover the legend, if the legend is in the way. 

<details><summary>video</summary>

https://github.com/VEuPathDB/web-monorepo/assets/24446573/35777a14-3cb1-4ae0-948e-33fe5bb9511f

The alternative looks wrong to me: 

https://github.com/VEuPathDB/web-monorepo/assets/24446573/1be9d344-2687-4bb3-9f99-166fc733a58a
</details>

<hr />

- [x] When there's a draggable visualization open, the most recently touched will be at the top of the stacking context.

<details><summary>video</summary>

https://github.com/VEuPathDB/web-monorepo/assets/24446573/a4e40a78-f1c3-4fe8-9934-42b4dd98e8ba

The alternative:

https://github.com/VEuPathDB/web-monorepo/assets/24446573/179f1b9b-4e2a-4cb1-86da-284b96ae839b
</details>

<hr />

- [x] When the panel resizes, there will be logic to make sure it's not off screen.
 
<details><summary>video of the problem I'm describing</summary>

https://github.com/VEuPathDB/web-monorepo/assets/24446573/a0ff00ab-ff1c-4fb5-bb38-baec7903bda1
</details>

**Comment by d-callan** [comment]
this appears to be complete.. im going to close and someone can reopen if i turn out to be wrong
