### ISSUE TITLE
Map: Need finalized map type icons

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#244]
We had previously had a markers menu item, and entries under it like 'donuts'. each entry had a rather wide icon featuring the type of marker in triplicate. as we move to a new 'map type' menu item in place of 'markers' we will need more condensed icons representing each map type.

**Comment by dmfalke** [comment]
Can this be closed? @asizemore @d-callan

**Comment by dmfalke** [comment]
Thank you!
