### ISSUE TITLE
Map: ez time filter

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#245]
This has been discussed in dataviz. requirements, partly subject to some change/ finalization, are these:
1. have a variable input
2. means to indicate for which values that variable does or doesnt have data visible on the map (using the width of the slider)
    - is this a separate component?
    - needs legend as well
3. has text inputs but also two thumbs on the slider, and either can define range start and ends
4. either thumb can move fully independently
5. arrows to shift the current bin end to the next bin start and vice versa while maintaining the bin width
6. if you click the blue box you can move the entire thing to a new part of the slider while maintaining your bin width

see tentative ex (with obvious room for ux improvements) here. 
![ez_time_filter](https://github.com/VEuPathDB/web-monorepo/assets/53306535/bf5821dd-05ed-48cb-8178-c4e0fc825aa5)

**Comment by d-callan** [comment]
worth noting, we may choose to phase these features in. their exact priority order isnt determined yet.

**Comment by d-callan** [comment]
we have updated mockups 


![Image](https://github.com/VEuPathDB/web-monorepo/assets/53306535/a54f3a32-5a8b-4f69-a661-1c26158d8713)

**Comment by moontrip** [comment]
> whoever works on this, just give me a ping when you need the icon!

@asizemore Thank you for your kind consideration. I think that the icon is not that urgent as I will be able to use any other icon for the time being - either way, I didn't even start SAM part either :)
