### ISSUE TITLE
Map and general: almost-unconstrained variables do not "explain" to users the default constraint against multi-valued vars

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#259]
At the moment the back end `apps` response contains the machine-readable constraints definition and a `description` prop that is presented to the user when they mouse-over a greyed out variable in the variable picker (`InputVariables`).

For example, the x-axis variable for a standalone-map scatterplot has this description:
> Variable must be a number or date and be the same or a child entity as the variable the map markers are painted with, if any.

Since (we will soon) closing https://github.com/VEuPathDB/EdaNewIssues/issues/635 we have an issue with the standalone map `map-markers` endpoint which has no `description` for the overlay variable - just the very basics:

```
{
	"overlayVariable": {
		"isRequired": true,
		"minNumVars": 1,
		"maxNumVars": 1
	}
}
```

The front end falls back to a default message: `'This variable cannot be used with this plot and other variable selections.'`

However, we should probably say that they are greyed out because we don't currently handle multi-valued variables.

Should we add a description to the back end response, or should we change the default message to mention multi-valued variables?

Opinions from @d-callan and @dmfalke would be gratefully received.

**Comment by dmfalke** [comment]
Are there any cases where we do support multi-valued variables? If not, I'm considering just appending the following to all constraint descriptions:

```
Muti-valued variables are not currently supported.
```

E.g.,

```
Variable must be a number or date and be the same or a child entity as the variable the map markers are painted with, if any. Muti-valued variables are not currently supported.
```

```
This variable cannot be used with this plot and other variable selections. Muti-valued variables are not currently supported.
```

The other approach I was thinking of is to check if the variable is multi-valued and to just say `Muti-valued variables are not currently supported.`. This will require some more work.

Thoughts?

**Comment by d-callan** [comment]
I don't currently support multi valued vas for any vizs and am happy w appending something to the current explanation.

**Comment by dmfalke** [comment]
Great, thanks!
