### ISSUE TITLE
Map: Add Bubble marker map type

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#263]
_Depends on #95 and #249 and #273 and https://github.com/VEuPathDB/EdaDataService/issues/260 and https://github.com/VEuPathDB/EdaDataService/issues/287_

Similar to donut and lineplot markers, we will need:
- A bubble marker configuration entry for the menu
- A bubble marker menu configuration component
- Logic to use the bubble marker legend
- Logic in `useStandaloneMapMarkers` to handle bubbles. Until the [backend plugin](https://github.com/VEuPathDB/EdaDataService/issues/260) is ready to use, we can use the response from `getStandaloneMapMarkers` to find the size of the bubble (sum up the `count` value).

**Comment by d-callan** [comment]
For dev against the existing map markers endpoint I would use the entityCount to size the bubble and take the first of the count values for the color. All you really need is two numbers to get started. 

Details on what the menu configuration will look like etc are pending.

**Comment by d-callan** [comment]
a thought i just had, which may need a separate ticket or mentioned somewhere else, is that we dont have an obvious way yet to show 0 values on the bubble map. id like to propose using a pin marker, and clarifying in the legend what they mean.



![Image](https://github.com/VEuPathDB/web-monorepo/assets/53306535/8f58fee2-ab13-4917-8f21-a2b5e495c0c3)

if wed like this could also be generalized to other point marker map types like donut and bar

**Comment by d-callan** [comment]
I'd be ok putting the first inside the pin. The thing I like about the pin is it's clear the location is important, but it's also not commonly associated w thematic mapping so people won't expect it to be a data marker, which leaves the markers we do use their coherence.

**Comment by dmfalke** [comment]
My concern with the pin marker is that it might look like a glitch, as if we forgot to style the default pin.

**Comment by d-callan** [comment]
customizing it a bit partly mitigates that, and putting it in the legend. people really cant avoid reading the legend..

**Comment by d-callan** [comment]
the bubble config will be like the line plot config for the yaxis. if a cont var is chosen, we will offer the same aggregation methods as the line plot 'mean', 'median', 'geometric mean'. if a cat var is chosen, we will allow a proportion to be configured. by default all values of the selected variable go to the denominator. see this ex



![Image](https://github.com/VEuPathDB/web-monorepo/assets/53306535/80e7e350-429f-4a16-a3a0-a0b482cd7c4c)

*note we dont actually have to show cat and cont config simultaneously as in the mockup.

we will offer the same floating vizs as the donut and bar modes, except these will not offer an overlay.

**Comment by d-callan** [comment]
i went ahead and made an issue for the pin marker https://github.com/VEuPathDB/web-monorepo/issues/273
