### ISSUE TITLE
EDA  Ranked abundance: clarify plot subtitle text

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#265]
Feedback from @dpbisme : The plot subtitle isn't very clear. Not sure what "variables" are.

Proposal: change to "Ranked abundance: X-axis variables with ..." for boxplot and "Ranked abundance: Overlay variables with... " for scatter

**Comment by dmfalke** [comment]
The configuration component is passed the `computation` and `visualizationId`, so it should be able to look up the visualization and figure out its type: https://github.com/VEuPathDB/web-monorepo/blob/7f136ad8de0eb6315496f417a205a7b1a92c00ec/packages/libs/eda/src/lib/core/components/computations/Types.ts#L18-L23

**Comment by asizemore** [comment]
Brilliant! Thanks @dmfalke !!

**Comment by asizemore** [comment]
Update:
The number in the plot subtitle for ranked abundance box and scatter has been fixed. So the scope of this ticket is now to just change "Ranked abundance: Variables with..." to "Ranked abundance: X-axis variables with..." for the box plot and to "Ranked abundance: Overlay variables with..." for the ranked abundance scatterplot. Hoping for a quick and easy update!
