### ISSUE TITLE
Map - low-cardinality variables should not be sorted by frequency

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#279]
Do we want to bypass the frequency-based sorting for low-cardinality variables? My guess is yes...

Here is a six-value variable from **SCORE S. mansoni**

As a marker overlay
![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/845b4a3b-b007-469b-b583-5d340ec91ca0)

In subsetting/filtering
![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/3a44bb7e-855c-4c93-96b3-d0813ebf706d)

**Comment by d-callan** [comment]
i think once we have advanced marker config showing things based on their frequency becomes the work of the markers configuration menu and never the legend

**Comment by bobular** [comment]
Still an issue. Not a show stopper.

Agree with Danielle - the marker configuration somehow needs to freeze the order for low-cardinality vars (and disable table sorting?)


![Image](https://github.com/VEuPathDB/web-monorepo/assets/308639/d8da6c1d-9b58-4a44-9976-09c05b184686)

**Comment by dmfalke** [comment]
> Still an issue. Not a show stopper.
> 
> Agree with Danielle - the marker configuration somehow needs to freeze the order for low-cardinality vars (and disable table sorting?)
> 
> ![Image](https://user-images.githubusercontent.com/308639/261623630-d8da6c1d-9b58-4a44-9976-09c05b184686.png)

I understood @d-callan's comment to be that the legend should not be sorted by frequency, but the marker preview table should continue to do so. I think I agree with this, just to keep the table consistent. I think we just need to make sure that the **Values** column is sorted based on the order from the variable's `vocabulary` property. Thoughts??
