### ISSUE TITLE
Dataset Access Requests: Allow a denied request to be edited and resubmitted

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#300]
specifics in https://redmine.apidb.org/issues/51673

This is related to backend work done for https://github.com/VEuPathDB/service-dataset-access/issues/64.

I will update this issue with more details sometime in the next 24 hours.

**Comment by nkittur-uga** [comment]
I tried this on MAL-ED and it worked properly. Couple of screenshots attached. Passes QA.
<img width="1217" alt="Screenshot 2023-09-01 at 9 58 33 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/67710160/501cc953-d665-4811-a192-e5ad5f7aa0a1">
<img width="1345" alt="Screenshot 2023-09-01 at 9 59 21 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/67710160/2e97798e-dc8f-4470-b537-0db49563bb9a">
