### ISSUE TITLE
make bubble map type icon

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#311]

**Comment by bobular** [comment]
The one just merged from Connor's PR looks good to me.
Is this done?

On a related note, I think the pen inside the map marker for "Configure map" is too subtle. I'd go for gear icon or something bolder. Thoughts (on Slack?)

![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/da531747-077b-4459-9c92-96ba5deb9151)

**Comment by asizemore** [comment]
yes this is done! (and i'm also in favor of the simple gear :) )
