### ISSUE TITLE
Polishing differential abundance

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#358]
Parent ticket for many (hopefully small!) polishing tasks for the differential abundance app:

- [x] Check to ensure no values overlap in groupA and groupB. So if "peanuts" chosen in group A, disable it in group B and add tooltip that says "Values cannot overlap between groups" or something  like that (credit @jernestmyers ) https://github.com/VEuPathDB/web-monorepo/pull/388
- [x] Add swap button to group A group B https://github.com/VEuPathDB/web-monorepo/pull/396
- [x] Add empty vizx plot. Otherwise the panel looks really weird before the viz data is ready. https://github.com/VEuPathDB/web-monorepo/pull/390
- [x] Add legend (driven by VolcanoPlot, always the same labels, no need to have it be clickable) https://github.com/VEuPathDB/web-monorepo/pull/392
- [x] Add axis controls to x and y axis. Component is ready. Just need axis range control, no log transform or anything! https://github.com/VEuPathDB/web-monorepo/pull/404
- [x] Add opacity slider for markers. https://github.com/VEuPathDB/web-monorepo/pull/404
- [x] Add axis truncation indicators (remember use props+data to derive this instead of state!) IP here https://github.com/VEuPathDB/web-monorepo/pull/325
- [x] update numberInputRange to take increment prop (right now changes by 1, but we need it to change by 0.001 or so) https://github.com/VEuPathDB/web-monorepo/pull/384
- [x] Layout inputs and such nicer (may require update to LabelledGroup) https://github.com/VEuPathDB/web-monorepo/pull/396

**Comment by jernestmyers** [comment]
Closing now that all sub-tasks have been merged.
