### ISSUE TITLE
Visualizations: truncation bars not showing

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#369]
Not sure what i did wrong here, but here's the autozoom
<img width="793" alt="Screen Shot 2023-07-18 at 10 52 47 AM" src="https://github.com/VEuPathDB/EdaNewIssues/assets/11710234/bf9e17d3-d1c2-4e12-ba13-79a9eabdbcec">

And here's me trying to get a truncation bar to show up. Sometimes it'll appear for a moment and then it will disappear. There should be one on the left side of the plot
<img width="847" alt="Screen Shot 2023-07-18 at 10 51 55 AM" src="https://github.com/VEuPathDB/EdaNewIssues/assets/11710234/6284846e-87af-4968-a034-d556750e6648">

**Comment by moontrip** [comment]
> Oh, this was a known limitation with a non-trivial, possibly back end IIRC, solution. @asizemore @moontrip

Thanks @bobular 👍 I missed your comment while commenting at PR 😅

**Comment by bobular** [comment]
No @moontrip after posting the above I saw on your PR that you had looked into the history of this issue. My apologies! I'm reviewing now.

**Comment by moontrip** [comment]
> Is this addressed by #376?

@dmfalke Sorry, I forgot to close this ticket. Yes, it was resolved by #376. Also, I think that the #376 also addressed long-lasting ticket, https://github.com/VEuPathDB/web-eda/issues/1295: can you please confirm this, @bobular?

**Comment by bobular** [comment]
> > Is this addressed by #376?
> 
> @dmfalke Sorry, I forgot to close this ticket. Yes, it was resolved by #376. Also, I think that the #376 also addressed long-lasting ticket, [VEuPathDB/web-eda#1295](https://github.com/VEuPathDB/web-eda/issues/1295): can you please confirm this, @bobular?

Yes, please also close 1295. It also mentions lineplot, but lineplot does not have "semantic zooming" so I don't the same problem applies.
