### ISSUE TITLE
Verbiage changes to Data Access Dashboard

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#407]
https://redmine.apidb.org/issues/51673

In b65, the data access dashboard will begin being utilized by people external to VEuPathDB. Because of this, we need to clarify some of the language on the Data Access Dashboard so that it is more intuitive to folks not associated with the project:

**Change “End Users” to “Data Requestors” in the section header and also in the buttons**
<img width="232" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/b0079076-e54b-4c22-93d2-fb33dfb62f52">

<img width="220" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/d9381f04-9051-4051-b2d4-7f0e1a2e1233">

**Change "Provider" to "Team member" in the buttons (in the "Study team member" section):**
<img width="208" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/80e86357-aa7a-4f0b-9bea-12c6e16aaf11">

**Change “Staff” to “VEuPathDB Staff in the header”**
<img width="254" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/fa417dd7-fc66-468a-a48d-283f88e6e83c">

**Change “End User Table Updates” to “Data Requestor Table Updates”**
<img width="236" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/7ec9b7f3-35d1-4565-a080-49fdb2886e2f">

**Comment by aurreco-uga** [comment]
committed in main,  will get pushed to qa sites soon.

**Comment by danicahelb** [comment]
looks good, closing
