### ISSUE TITLE
EDA : provide user friendly way to view geolocated clinepi & mbio studies in SAM

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#410]
https://redmine.apidb.org/issues/51836

ClinEpi & Mbio sites need a straightforward way to allow users to access data on the stand-alone map, ideally by b65. 

see this related redmine ticket: https://redmine.apidb.org/issues/51836. Nupur had the idea to add a link under the Workspace menu in the header to bring up essentially a "my analyses" table where analyses could be opened in the SAM. This is not straightforward enough, as the user would first need to make an analysis in ClinEpi and then find the appropriate link to see all SAM analyses and then open the correct analysis.

I propose that the link under the Workspace menu should allow users to access ALL studies with GIS data (ie, any study where the map viz tool is active), so that they can open the study in the SAM and apply filters directly there.

This has been implemented on qa.restricted only

<img width="555" alt="image" src="https://github.com/VEuPathDB/web-monorepo/assets/25450900/bf84592a-b263-46a1-a177-9039c44c6bfd">

Alternatively, we could add a button on either the viz tab or within the map viz tool itself that would shift the analysis from being presented in the EDA to the SAM. this would require that any filters applied in the EDA also be active when the analysis shifts over to the SAM. And we would need a button in the SAM to bring the user back to the same analysis in the EDA

**Comment by dmfalke** [comment]
We will need a way to know if a dataset has map data. The easiest way would be to add a new dataset attribute. That way the front end code can check this attribute to decide if a map icon is also needed, when rendering the studies menu.

@jbrestel may have some thoughts on this. We have a similar need for the genomic sites, for which he suggested a new WDK question. I think a new dataset attribute would be more flexible and would work for both cases.

**Comment by dmfalke** [comment]
We have decided to table this request, given the new links in the EDA tabs, and the SAM header.
