### ISSUE TITLE
bubble marker mode: make legends more stable to re-rendering

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#417]
Legends should only re-render when the variable or variable config (e.g. num/denom or median/mean) has changed, or probably also general filters.

- [ ] look at dependencies of the legends and prevent rerendering
- [ ] avoid shrinking between variable-changes?
- [ ] while we're here
      - [ ] figure out solution to major waste of space (see below) when variable name is long (ellipses are fine with me)
      - [ ] can we shrink the Count legend a bit? Is the max bubble size really straight from the back end (as `bubbleLegendData.maxSizeValue`)? And is that based on the the total filtered entity count (as if there was a geohash_0 level) as @chowington explained yesterday? I think it should be geohash_1 based. @dmgaldi ?

![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/39ee2370-0aae-4e11-976b-96585642c1d1)

**Comment by dmgaldi** [comment]
As it stands, the variable that's used by the backend is passed as input:

```
        "sizeConfig": {
            "geoAggregateVariable": {"entityId":"GAZ_00000448","variableId":"EUPATH_0043203"}
        }
```

There might be advantages to just selecting the desired geohash (geohash_1 presumably) on the backend, though I'm not sure how the different levels are distinguished in the study metadata. For now, I think the front-end can pass geohash_1 instead of geohash_0 assuming that's what's being passed now.

**Comment by bobular** [comment]
Thanks - let me have another play. There is no `geohash_0` currently - it's just a way of saying "whole map, no geohashing", which I thought from what Connor said on Wednesday was how the max bubble size/count was determined.

**Comment by dmgaldi** [comment]
I see, it's supposed to based on the max aggregate count value of the geohash level passed as input to the legend endpoint.  If it's behaving as a "geohash_0", let me know. It's probably indicative of a bug.

**Comment by bobular** [comment]
It's not a bug - there's some rounding happening in the client that is creating bigger legends than we ideally need. Looking into that now!

**Comment by bobular** [comment]
Won't fix on this side of the refactor!
