### ISSUE TITLE
EDA ClinEpi: add scale to display labels

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#450]
We are using “scale” annotation in the owl file to indicate whichever type of log (log2, log10, ln, etc.) the data has been loaded in.
"Scale" information should be added to the display label, in a similar manner to how units are being added. 

If the label has units, the type of log should be added in the parentheses & separated from the units by a comma. For example: Alpha-1-antitrypsin (ln, mg/g)

see also https://redmine.apidb.org/issues/43947

**Comment by ryanrdoherty** [comment]
@dmfalke Backend changes are now in dev and can be put on QA by upgrading eda-subsetting in tagger to 3.11.0.
