### ISSUE TITLE
site search typeahead: keep users history in dropdown

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#463]
https://redmine.apidb.org/issues/41118

options discussed:
- user clicks ans sees thir history but when typing the offering is the same for everybody
- OR
- we combine history with offering....

**Comment by dmfalke** [comment]
I suggest the following:
- Store history in localstorage (maybe limit it to 10 or 20?)
- Only show history if input is focused, blank, and history is not empty
- Offer a "Clear history" option
- Once the input is not empty, only show typeahead suggestions

**Comment by aurreco-uga** [comment]
dave: localstorage per website?
so this could be done in main and released independently of releasing typeahead?
or would it be done in the same branch (typeahead) and check together before merging?

**Comment by dmfalke** [comment]
> dave: localstorage per website? so this could be done in main and released independently of releasing typeahead? or would it be done in the same branch (typeahead) and check together before merging?

I think per-website. Otherwise, we have to worry about merging things when a user logs in, etc.

I would do this on the same branch.
