### ISSUE TITLE
vectorbase tools map menu: if only one study do not show grouping

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#466]
omar requested ta standup Aug 31 2023

**Comment by dmfalke** [comment]
Isn't this a temporary situation? Or are we only going to release one study for b65?

**Comment by bobular** [comment]
I think for b65 the only study will be the megastudy, but I'm personally happy to future-proof it and make our dear user click one more time ;-)

**Comment by dmfalke** [comment]
I did this in #474
