### ISSUE TITLE
EZ time slider brush is adversely affected by parent draggable panel's position thanks to a CSS `transform`

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#480]
Making a separate issue so I don't get bogged down. But I have identified the issue at least!

To replicate:

- Time slide currently only in this branch: https://github.com/VEuPathDB/web-monorepo/pull/320
- Move the slider to the left of your screen
- Shorten the selection with the handles
- Now draw a new selection in an unselected area
- It should work fine
- Now move the draggable panel over by, say, 300px
- Now draw a selection and you'll see it's all offset by 300px.

This is caused by the CSS `transform` that is used by our react-draggable thingy.

Can we fix this somehow?

**Comment by dmfalke** [comment]
This apparently due to a bug in Firefox (see https://stackoverflow.com/questions/37666242/parent-css-transform-affecting-d3-mouse-points). For now, we should probably avoid using a draggable panel.

**Comment by bobular** [comment]
Closing as non-issue now we are not using a draggable
