### ISSUE TITLE
Map - non-existent analyses do not load and just give a blank page

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#518]
You can test this with the following link https://vectorbase.org/vectorbase/app/workspace/maps/DS_480c976ef9/abcdefg

There's a 404 on the user analysis back end request but nothing is communicated to the user.

I found this problem with a on old browser tab. I'm not sure what happened to the analysis, but I think it's happened more than once and I don't think I've been deleting any analyses. I will monitor it.

Let's try to keep the SAME UX as in https://qa.clinepidb.org/ce.b31/app/workspace/analyses/DS_8e1f623542/qNlghhjjkk, currently attached below. 
Better would be a message saying: "this analysis does not belong to you. If someone is trying to share an analysis with you, ask that they use the "share" button to give you a short URL  such as: https://qa.clinepidb.org/analysis/qNlghhjjkk"

**Comment by dmfalke** [comment]
I'm beginning to work on this. I'm trying to work out what the UI should look like. Some options are:
1. Render a standard not found or error page (e.g., https://vectorbase.org/vectorbase/app/404, https://vectorbase.org/vectorbase/app/500)
2. Render the map interface (header and leaflet map), but with an overlay indicating analysis not found or error loading.

I'm leaning towards (2), as it's more clear, but it will be more work (medium cost). @bobular do you have thoughts on this?

**Comment by bobular** [comment]
I like 2!
Would it have a "click here to start a new analysis" link or button?

**Comment by dmfalke** [comment]
That's what I was thinking!

**Comment by aurreco-uga** [comment]
there is third option: to tell the user that this analysis does not belong to them. I think this information is important.
also we have the same issue in EDA, see attached.

![Screen Shot 2023-11-09 at 6 18 39 PM](https://github.com/VEuPathDB/web-monorepo/assets/16354313/d7f3dc10-8e74-4a5b-ad63-7cb202c76bbf)

**Comment by bobular** [comment]
Just tested the link at the top of this issue and this looks/works great!
