### ISSUE TITLE
Differential Abundance: improve layout of compute config

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#531]
We've recently added a new input to differential abundance computes, to allow explicitly selecting an analytical method. the new input is there, and functional....... but very ugly and unclear. i think maybe we need some mockups @asizemore ? and @jernestmyers has kindly offered to do the ui work once we have decided how things should look.

**Comment by asizemore** [comment]
Closing as we've decided to remove the Method input completely. See #543
