### ISSUE TITLE
Variable Collection in Computes: recent API change anticipated to break saved analyses

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#532]
Ive recently merged some changes that are anticipated to break saved analyses, but will allow us to more fully support variable collections (access their annotation properties, etc) in the computes. we need to figure out how we mean to handle this so that the saved analyses continue to work come release time.

**Comment by ryanrdoherty** [comment]
@d-callan Is the issue with broken analyses that a user has selected a collection that is no longer compatible with the compute (but was before)?  If so, that doesn't seem like something we can migrate.  We would just have to tell the user to pick a different collection in the UI (assuming UI can detect that old collection ID does not conform to new constraints imposed by the newly supported metadata).  Am I way off base (I am basically guessing after all) or does all this sound accurate?

**Comment by d-callan** [comment]
So the backend has been using variableSpec rather than collectionSpec for a while. That's presumably bc the first app predated formal variable collections and it just didn't matter until now. Now, I need access to collections specific annotations and so I switched to collctionSpecs. That means that we have a lot of requests in saved analyses with 'variableId' where they should have 'collectionId'.

**Comment by ryanrdoherty** [comment]
Aha, great!  Sounds like this is a candidate for migration after all then.  Should not be a big deal, esp if you know exactly which computes/viz configs need to be migrated.
