### ISSUE TITLE
Header disappears when viewport width is < 1013px

### ISSUE THREAD

**Issue by adnauseum** [VEuPathDB/web-monorepo#536]
The header is expected to be sticky and follow along as a user scrolls down in a given site. At the moment the header vanishes whenever the viewport width is < 1013px.

![Header Bug Small](https://user-images.githubusercontent.com/24446573/213338958-2f04bd86-9919-4750-91d8-3d7ea3d8e0fd.gif)

<img width="1352" alt="Screen Shot 2023-01-18 at 7 44 25 PM" src="https://user-images.githubusercontent.com/24446573/213336853-0ea5ed3e-b52e-446d-aa24-06ff2463e1c7.png">
<img width="1352" alt="Screen Shot 2023-01-18 at 7 45 14 PM" src="https://user-images.githubusercontent.com/24446573/213336910-7c645668-1990-40b4-a56f-0473471f1d24.png">

**Comment by aurreco-uga** [comment]
i think this was done on purpose
