### ISSUE TITLE
Remove "User" from references to user studies in EDA

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/web-monorepo#55]
In [the 2023-04-10 EDA UX meeting](https://veupathdb.atlassian.net/wiki/spaces/FG/pages/235896833/Monday+2023-04-10+1PM), it was decided to reference user studies on the page as `My Studies` or `My Study` instead of the current `My User Studies` or `My User Study`.

Please update all instances where we refer to `User Stud(y/ies)` by removing `User` from the string.

**Comment by danicahelb** [comment]
Screenshots of places needing updating:

<img width="196" alt="image" src="https://user-images.githubusercontent.com/25450900/232647224-b4d9d4a1-389e-4e26-b513-98a313f101a5.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/25450900/232647316-dcd3efdd-82b8-43ff-8661-2a4f686dc38a.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/25450900/232647429-abed4b33-8a89-47b3-935b-f6345954b756.png">

**Comment by danicahelb** [comment]
related ticket: https://github.com/VEuPathDB/web-monorepo/issues/80

**Comment by SAK22** [comment]
Looks good!
