### ISSUE TITLE
microbiome saved analyses computes broken

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#551]
Making an issue here so that we don't lose track of it...

As discussed in #526 , the updated API means that the saved analyses will have compute apps that now say they need to be configured. Example below from May.

<img width="858" alt="Screen Shot 2023-10-13 at 5 20 27 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/11710234/cde20fc9-11da-4752-87c0-82f63b181d99">

Selecting the plot just brings me to the plot but i need to reselect the data. No errors at least. How do we want to resolve this? Or is any action necessary?

**Comment by dmfalke** [comment]
Is this related to #532? If so, seems like we could also populate the compute method during the database migration.
