### ISSUE TITLE
WDK strategy workspace: fix verbiage

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#554]
we dont link to a youtube video..

<img width="1189" alt="strat-fix-message" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/d8c83ae3-859e-4260-a57e-ad636ff82aeb">

**Comment by jernestmyers** [comment]
Should I delete any mention of a YouTube video? I briefly looked at our YouTube videos and didn't see one pertinent to this messaging.

**Comment by dmfalke** [comment]
> Should I delete any mention of a YouTube video? I briefly looked at our YouTube videos and didn't see one pertinent to this messaging.

I must have added this as a placeholder at some point. I don't recall if there was a plan to add a tutorial or not.
