### ISSUE TITLE
study access service: make data access dashboard button more prominent

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#567]
we should “unhide” the button to open the data access dashboard… we've now handed over access management to the teams and the current location is too hidden

Make a new tab labeled “Manage study” that is only visible to provider-managers (and VEuPathDB staff) when logged in. Styling of this tab should be different so that this tab (only visible to managers) is differentiated from the other tabs (always visible to all users). Perhaps make the tab the same coloring as the button?

Once the new tab is implemented, delete the button from the study details tab

<img width="1428" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/922a575e-6779-4053-b651-09296f34a677">

**Comment by danicahelb** [comment]
All of the information on the study access page (ie, https://clinepidb.org/ce/app/study-access/DS_8e1f623542) should be on the new "Manage study" tab

<img width="666" alt="image" src="https://github.com/VEuPathDB/service-dataset-access/assets/25450900/01aa5749-2298-4a17-bfbc-5fcfb4487b83">

**Comment by dmfalke** [comment]
@danicahelb what if we move the button next to the study name in the analysis header, and skip making the new tab?

![image](https://github.com/VEuPathDB/web-monorepo/assets/365139/7cbf109e-b51f-4094-8a8f-7c72e8a539bb)

**Comment by danicahelb** [comment]
yes, that is fine

**Comment by danicahelb** [comment]
can we push this to the live site as soon as it is QA'd (ie, not wait to b67 release)?

**Comment by dmfalke** [comment]
> can we push this to the live site as soon as it is QA'd (ie, not wait to b67 release)?

That should be doable. @chowington I can handle that, since the process is pretty verbose.
