### ISSUE TITLE
analysisID not found

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#587]
i was in my analysis (as guest), clicked on veupath icon (idea to log in) then i remembered i could login from wihin eda, hit teh back button and got analysis not found .
i was still the same guest user.. and the analysis does exist in user database and belongs to me.. 

<img width="1169" alt="Screen Shot 2023-11-02 at 1 47 32 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/e5704fa7-b9de-4c31-a52d-72a090d3c25d">

**Comment by aurreco-uga** [comment]
sorry this belongs in the service...

**Comment by dmfalke** [comment]
This was due to the eda service issuing a set-cookie header that conflicted with the wdk service, which results in the browser being assigned a new guest user.
