### ISSUE TITLE
(on Systems) EDA :  analysis ID not found when leaving EDA workspace and coming back: new guest user

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#602]
Passed to systems based on daves feedback:  https://redmine.apidb.org/issues/53027

i was in my analysis (as guest), clicked on veupath icon (idea to log in) then i remembered i could login from within eda, hit the back button and got analysis not found  (see at the bottom the request for the analysis ySW..  in red )
i was a different  guest user.. 
<img width="1169" alt="Screen Shot 2023-11-02 at 1 47 32 PM" src="https://github.com/VEuPathDB/stack-eda-services/assets/16354313/21169859-5752-4629-a9e5-b7be3dba3548">

**Comment by dmfalke** [comment]
I can't reproduce this

**Comment by dmfalke** [comment]
It looks like prod is not using path cookies for `/eda`. Note, in the image below, the response cookie for https://vectorbase.org/eda/studies/VBP_MEGA/entities/OBI_0000659/variables/EUPATH_0043256/distribution includes a JSESSIONID cookie with a path value of `/`, but should be `/eda`.
![image](https://github.com/VEuPathDB/web-monorepo/assets/365139/9bc41ed6-d18b-494f-b564-52e8c546b158)

**Comment by dmfalke** [comment]
Looks like this has been fixed
