### ISSUE TITLE
Variable sorting doesn't handle `displayOrder` values of zero

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#626]
`displayOrder` variable annotations of zero are valid and are loaded and served by the EDA back end:

![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/72ab1122-2a9b-4727-8964-63b0abce3002)

However I believe that

SubSettingClient/index.ts
```
// !!MUTATION!! order variables in-place
function orderVariables(study: StudyMetadata) {
  for (const entity of preorder(
    study.rootEntity,
    (entity) => entity.children ?? []
  ))
    entity.variables.sort((var1, var2) => {
      if (var1.displayOrder && var2.displayOrder)
        return var1.displayOrder - var2.displayOrder;
      if (var1.displayOrder) return -1;
      if (var2.displayOrder) return 1;
      return var1.displayName < var2.displayName
        ? -1
        : var1.displayName > var2.displayName
        ? 1
        : 0;
    });
  return study;
}
```

Needs tests for `varX.displayOrder` changing to `varX.displayOrder != null`.

Then this `protocol` variable would be sorted to the top, as intended:
![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/1ed39ef6-60e2-47ee-a256-d2dbe39bbae0)

**Comment by dmfalke** [comment]
@bobular I have some concerns about making a change like this. Do you know if the value `0` is only used when specifically defined? Do we know every place that it's currently being used, and that this change will be good, or is it possible that this will change the order of variables in an undesirable way in some places?

Out of curiosity, why do we need to support a value of `0`? Can't we just use `1`, and add `1` to other values, if something needs to be given higher priority?

**Comment by bobular** [comment]
Why shouldn't sort order be from minus to positive infinity?

**Comment by bobular** [comment]
displayOrder annotations are made manually I think in most cases.  Do we really want the curator to have to add one to each when they could add a new one at 0, and later another one at -1, etc?

**Comment by dmfalke** [comment]
I'm convinced. Thanks!
