### ISSUE TITLE
MAP: qa.vb :  timeseries plot throws error when zooming in -  lineplot has no data

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#635]
https://qa.vectorbase.org/vectorbase.b66/app/workspace/maps/0iERquy/import

unzooming works, when zooming you get the error

<img width="1269" alt="Screen Shot 2023-11-12 at 7 28 39 AM" src="https://github.com/VEuPathDB/stack-eda-services/assets/16354313/7b16511e-a484-4cc5-a2ea-8c88651d8699">

**Comment by dmfalke** [comment]
Looks like an io-ts error, from the screenshot

**Comment by jernestmyers** [comment]
I opened https://github.com/VEuPathDB/EdaDataService/issues/331 in relation to my investigating this issue. I'm hesitant to make any client changes before getting clarity on the inconsistent responses.

**Comment by dmfalke** [comment]
I suspect we won't need to make any client changes.

**Comment by aurreco-uga** [comment]
seems fixed
