### ISSUE TITLE
ClinEpiDB - Strange behavior with Studies menu section collapsed state

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#642]
I noticed that the collapsed state of the sections in the Studies menu has a strange interaction when the filter is used. Perhaps it's related to React keys? See the screencast below:

[Screencast from 2023-11-14 15-30-17.webm](https://github.com/VEuPathDB/web-monorepo/assets/365139/907900f7-26ea-42be-9a79-a0e540fdb917)

**Comment by aurreco-uga** [comment]
looks like when filtering it changes the section state: if closed, it opens, or if opened it closes it..
