### ISSUE TITLE
Studies dropdown menu: My studies and Curated studies sections always should be open (remove ability to close)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#648]
On qa.restricted.clinepi, the studies dropdown looks like this, with `My studies` closed initially and `Curated studies` opened initially
<img width="570" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/1b942e0a-4be7-4824-bdc1-b70bcb6f9b79">

If I use the search bar (ex: search for avenir), this causes `My studies` to disappear and `Curated studies` to close (such that I cannot see the study I searched for without opening it up)
<img width="245" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/9bb054cc-55a8-444d-b40e-76622fb3e33e">

Please change the functionality of this so that `My studies` and `Curated studies` are always open (there is no need to close these sections).
If I search for a study, please keep the `My studies` and `Curated studies` headers, but just show the studies that meet the search below the headers

**Comment by dmfalke** [comment]
This is related to #642. @jernestmyers if we want to retain the ability to collapse, I think we should force these sections to be open when the studies are being filtered.

@danicahelb if we implement my suggestion, would you be okay with keeping the collapsible behavior?

**Comment by jernestmyers** [comment]
> if we want to retain the ability to collapse, I think we should force these sections to be open when the studies are being filtered.

I agree, and actually implemented this yesterday (but didn't yet push). However, I did not retain the "My studies" or "Curated studies" headers when no studies match. If desired, it wouldn't be difficult to render a "No results" string under a section with no matches. I'm not sure it's necessary, but it's an easy change nonetheless!

Here's a screencast of current behavior, which opens the sections when filtering and defaults both sections to be open when the page loads:
https://github.com/VEuPathDB/web-monorepo/assets/69446567/476c80f8-191f-4d3a-b884-fbe7b0bb0bb6
