### ISSUE TITLE
Volcano: add truncation warnings

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#69]
If a user sets the range so small that data points will be left out, we should show truncation indicators on the plot.

The question is... should we implement the same yellow boxes we don't like for consistency? Or move away from the boxes and show a pattern instead (easier with visx)? Has the time come to move to a new truncation warning indicator??

@d-callan @bobular

**Comment by d-callan** [comment]
How much would it cost to implement a pattern everywhere, if possible? I do want to be consistent..

**Comment by asizemore** [comment]
a few people have tried and found it's basically impossible with plotly. So it'd be only consistent across our visx plots.

**Comment by d-callan** [comment]
...... is it obnoxious to support both for the visx components, to give us the option of consistency in contexts where we are using plotly components as well?

**Comment by asizemore** [comment]
hmmm. no i don't think so... either way we're drawing a rectangle and filling it with something. So outside the extra prop existing it's not so bad!
