### ISSUE TITLE
Map - sub-studies information for megastudies (issue WIP)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#696]
This will change the top-right part of the header

Mockups are [here](https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?type=design&node-id=1926-42&mode=design&t=TZqeVOCAs4PT7R7D-0) (but screenshots below tell the whole story)

### Detecting megastudy vs regular study

The client asks if the root entity is a GeoEntity
* yes = regular study
* no = megastudy

This might not always hold true but it will avoid us having to hard-code in the study entity ID.

### Header for regular studies

We could either keep the current mini table (All, Filtered, View counts) or go for a new streamlined look:

![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/e535e6df-5e6d-41e1-8a85-d36e51070737)

This would be equivalent to the current "View" count.

The ℹ️ icon would provide the following nicely formatted tooltip text (between the horizontal rules):

---
1,234 <output entity name(s)> are currently visualized on the map using markers. These are the <output entity name(s)> that
- satisfy all your filters (you currently have X filters active)
- to do: also time slider filter
- have data for the <variable name> variable that is currently displayed on the markers
- have appropriate values for <variable name> if the marker has been custom-configured
---

The "appropriate values" text could be spelled out for the different marker modes more explicitly if we like.

### Header for megastudies

![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/ab91364b-acca-404a-879e-8c62830723ce)

ℹ️ icon text

---
1,234 <output entity name(s)> are currently visualized on the map using markers. These are the <output entity name(s)> that
- satisfy all your filters (you currently have X filters active)
- to do: also time slider filter
- have data for the <variable name> variable that is currently displayed on the markers
- have appropriate values for <variable name> if the marker has been custom-configured

The visualized data comes from 56 <root entity name(s)> [button="Show list"]

---

The `Show list` button would bring up a DraggablePanel on top of the map containing a simple clickable list of studies (see below). 

### How does the client get the number/list of relevant studies?

I think this will need to be a new request to (`studies/.../tabular`?) that includes 
- regular filters
- viewport filter
- time slider filter
- little filters generated from current marker mode configuration
  - default configuration, this will be `[MIN to MAX]` for continuous vars, and `value in [ALL VALUES]` for categorical
  - custom configuration for categoricals, `value in [DENOMINATOR VALUES]`

For the fields in the output, we ask for the first variable of this entity (ordered by displayOrder if available). This is supposed to be Study name for the megastudy.

I'm not liking the `[ALL VALUES]` for variables like species... (which ironically doesn't need it because there are no missing values for this variable)

Do we just make this request and use the number of rows/records for the header number? That way we can re-use the same request for the floating table below:

**Alternative approach?** Use map-markers endpoint and ask for outputEntity=Study

### The new floating table

A simple list of the tabular response as described above. Should respond to marker-selections.

If we're showing study names, are we linking using that, or the entity's row ID (the one that downloads displays)?

Links should go to the WDK record page. How are we doing that?

Will we need some hardcoding anyway to make sure we only make links when we have megastudy study entities?

**Comment by dmfalke** [comment]
> This will change the top-right part of the header
> 
> Mockups are [here](https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?type=design&node-id=1926-42&mode=design&t=TZqeVOCAs4PT7R7D-0) (but screenshots below tell the whole story)
> ### Detecting megastudy vs regular study
> 
> The client asks if the root entity is a GeoEntity
> 
>     * yes = regular study
> 
>     * no = megastudy
> 
> 
> This might not always hold true but it will avoid us having to hard-code in the study entity ID.
> ### Header for regular studies
> 
> We could either keep the current mini table (All, Filtered, View counts) or go for a new streamlined look:
> 
> ![image](https://private-user-images.githubusercontent.com/308639/287769134-e535e6df-5e6d-41e1-8a85-d36e51070737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODkyMDYsIm5iZiI6MTcwMjQ4ODkwNiwicGF0aCI6Ii8zMDg2MzkvMjg3NzY5MTM0LWU1MzVlNmRmLTVlNmQtNDFlMS04YTg1LWQzNmU1MTA3MDczNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNzM1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjU3M2M4MjA0OTAwZGZkNjE4MzU2OTBiOWNjZDM0YWEzMTZlZjE3MzY0ZTE3ZDVkMGNlM2YxYmNmNTI5OTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.by7iE2Xx_h2K6KK8DPXAs-HbKW1Bm7RtLZsiVwaTDjE)
> 
> This would be equivalent to the current "View" count.
> 
> The ℹ️ icon would provide the following nicely formatted tooltip text (between the horizontal rules):
> 
> 1,234 <output entity name(s)> are currently visualized on the map using markers. These are the <output entity name(s)> that
> 
>     * satisfy all your filters (you currently have X filters active)
> 
>     * to do: also time slider filter
> 
>     * have data for the  variable that is currently displayed on the markers
> 
>     * have appropriate values for  if the marker has been custom-configured
> 
> 
> The "appropriate values" text could be spelled out for the different marker modes more explicitly if we like.
> ### Header for megastudies
> 
> ![image](https://private-user-images.githubusercontent.com/308639/287774938-ab91364b-acca-404a-879e-8c62830723ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODkyMDYsIm5iZiI6MTcwMjQ4ODkwNiwicGF0aCI6Ii8zMDg2MzkvMjg3Nzc0OTM4LWFiOTEzNjRiLWFjY2EtNDA0YS04NzllLThjNjI4MzA3MjNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNzM1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjM5MjZlNDhmOGExOTRhY2E3NjBmMDZlMjkxNmY2ZDZjZTJkMjM0Nzg5NzE3ZWI5ZDc0NWY1NmIyNDg1NDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yIDQyhJAOSc_o0fAIVShBliGaKId3WH1CL6eh9leizo)
> 
> ℹ️ icon text
> 
> 1,234 <output entity name(s)> are currently visualized on the map using markers. These are the <output entity name(s)> that
> 
>     * satisfy all your filters (you currently have X filters active)
> 
>     * to do: also time slider filter
> 
>     * have data for the  variable that is currently displayed on the markers
> 
>     * have appropriate values for  if the marker has been custom-configured
> 
> 
> The visualized data comes from 56 <root entity name(s)> [button="Show list"]
> 
> The `Show list` button would bring up a DraggablePanel on top of the map containing a simple clickable list of studies (see below).
> ### How does the client get the number/list of relevant studies?
> 
> I think this will need to be a new request to (`studies/.../tabular`?) that includes
> 
>     * regular filters
> 
>     * viewport filter
> 
>     * time slider filter
> 
>     * little filters generated from current marker mode configuration
>       
>       * default configuration, this will be `[MIN to MAX]` for continuous vars, and `value in [ALL VALUES]` for categorical
>       * custom configuration for categoricals, `value in [DENOMINATOR VALUES]`
> 
> 
> For the fields in the output, we ask for the first variable of this entity (ordered by displayOrder if available). This is supposed to be Study name for the megastudy.
> 
> I'm not liking the `[ALL VALUES]` for variables like species... (which ironically doesn't need it because there are no missing values for this variable)
> 
> Do we just make this request and use the number of rows/records for the header number? That way we can re-use the same request for the floating table below:
> 
> **Alternative approach?** Use map-markers endpoint and ask for outputEntity=Study
> ### The new floating table
> 
> A simple list of the tabular response as described above. Should respond to marker-selections.
> 
> If we're showing study names, are we linking using that, or the entity's row ID (the one that downloads displays)?
> 
> Links should go to the WDK record page. How are we doing that?
> 
> Will we need some hardcoding anyway to make sure we only make links when we have megastudy study entities?

Some thoughts on this:

1. For the count in the header, I think we can just use the [count endpoint](https://veupathdb.github.io/EdaSubsettingService/api.html#resources:/ss-internal/studies/{study-id}/entities/{entity-id}/count:post). I'm assuming this will be more efficient than the [tabular](https://veupathdb.github.io/EdaSubsettingService/api.html#resources:/ss-internal/studies/{study-id}/entities/{entity-id}/tabular:post) counterpart.
