### ISSUE TITLE
Map - timeslider tooltip verbiage should mention that it is visualising data for the whole world not just the viewport

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#722]
Probably just by adding `(anywhere in the world)` to the first bullet item?

**Comment by moontrip** [comment]
Hi @bobular 
I checked the pre-existing tooltip, and its first bullet is "Black bars indicate when in time there is available data", so how about making the second bullet (instead of the first one) like "Data is visualized for the whole world, not the viewport"? Any suggestion is welcome 😃

**Comment by bobular** [comment]
Hi @moontrip 
I just saw that this tooltip text is now out of date since the "little filters" stuff was merged. I will add something similar to your suggestion also, and hope it gets in for the release.
