### ISSUE TITLE
XY Relationships Scatter sending computeConfig when it shouldn't

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#735]
Seen with `main`
<img width="1076" alt="Screen Shot 2023-12-15 at 6 32 27 AM" src="https://github.com/VEuPathDB/EdaDataService/assets/11710234/a099b2aa-e5aa-48d3-ab38-dd87d0e42a48">

The above was made in the XY Relationships "app". We're sending a null computeConfig with the request but we shouldn't be sending anything at all for that slot.

**Comment by asizemore** [comment]
Note this is _not_ broken on the live site

**Comment by dmfalke** [comment]
This is definitely due to changes in https://github.com/VEuPathDB/web-monorepo/pull/729. I will address there.
