### ISSUE TITLE
Map - make zoom less granular

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#763]
From a request from DSR:
> Can we make map zooming more continuous?  It is annoying not to be able to set at will.

We should be able to use fractional zoom levels - perhaps granularity 0.25
https://leafletjs.com/examples/zoom-levels/

Need to check that this doesn't have any unintended side-effects, such as
* more `map-markers` data requests
* ...
*

**Comment by dmfalke** [comment]
Is the issue of locking related to the geohash lookup? Does rounding resolve that particular issue?

**Comment by chowington** [comment]
@dmfalke Yes, the geohash lookup was the problem. Accounting for float numbers fixes the issue 👍
