### ISSUE TITLE
Display “+ New visualization” link on all visualization pages

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-monorepo#766]
When you make a visualization in the EDA and want to make another one, you need to click back to the "Visualize" homepage in order to see the “+ New visualization” link. This is not intuitive. It would be good to always display “+ New visualization” link on every visualization page. 

![Screenshot 2024-01-09 at 2 50 32 PM](https://github.com/VEuPathDB/EdaNewIssues/assets/67710160/f026f45f-496d-4c9d-83af-d6f95f979a83)

![Screenshot 2024-01-09 at 2 52 02 PM](https://github.com/VEuPathDB/EdaNewIssues/assets/67710160/81f97d87-95e9-4fa9-8367-7951a1a81793)

**Comment by danicahelb** [comment]
closing this ticket, we have this flow approved already, just need to implement: https://github.com/VEuPathDB/web-eda/issues/1122
