### ISSUE TITLE
Bipartite network: adjust legend when only a few edges exist

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#768]
Found with a user dataset while working on a separate issue, but this problem would affect all datasets. 

The stroke width legend is set up to always show 4 legend items. This doesn't make a lot of sense when there are four or fewer links, as seen below.
<img width="1351" alt="Screen Shot 2024-01-12 at 5 33 48 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/11710234/fad78d5c-7665-4519-9249-ce298b80a332">

Options
1. If there are four or fewer links, make one legend item per link. Just straight up show the actual value and stroke width for each link
2. If there are 3-4 links, no change. So a user would still see a range of equally spaced stroke widths from max to min, even if the 1 or 2 non max/min stroke widths are not exactly items in the legend. If there are 2-1 links, just make one legend item per link. 

I'm leaning toward option 1 because stroke widths are difficult enough to visually discern, so why not just give folks the actual matched stroke width in the legend. But I think @chowington and @d-callan might have opinions.

**Comment by d-callan** [comment]
I think it'd be if there are four or fewer links then show one legend item per unique weight, to some number of significant digits..
