### ISSUE TITLE
Export plots as SVG

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#780]
This was a common user request at a recent workshop

**Comment by dmfalke** [comment]
I'm running into some issues with exporting to SVG. The SVG will display just fine in a browser, but appears empty in an image viewer. Exporting to PNG works fine. Perhaps exporting to PNG is okay for now?

**Comment by d-callan** [comment]
I think he wants to fiddle w the images in something like adobe illustrator, so I'm guessing png is less than ideal.
