### ISSUE TITLE
Mbio apps: Add in-line user-facing documentation

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#781]
There are a lot of places wed like to do some explaining for the computes. some things that come to mind immediately:
1. Tell people were using pcoa in beta div, and why and what it might be good or bad at
2. Tell people what parameters were using w maaslin2 in diff abund, and why and what it might be good or bad at
3. Tell people about correlation methods used in the correlation apps, particularly once we introduce compositional methods for taxa-taxa
4. Tell people what prefilters were using for features in correlation apps
5. Tell people where they can find the R if theyd like
6. Other things i havent thought of yet

**Comment by asizemore** [comment]
is this a duplicate of https://github.com/VEuPathDB/web-monorepo/issues/771?

**Comment by d-callan** [comment]
maybe. i didnt see that one on the mbio tab of the project board, but did see [this](https://github.com/VEuPathDB/web-eda/issues/1563) and if im honest was generally a bit confused.

**Comment by d-callan** [comment]
added these thoughts to the other, and closing this
