### ISSUE TITLE
Side panel closes automatically after markers load

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#786]
I just noticed this. I think it's a recent bug. I was trying to change the marker variable when the side panel closed, which is pretty bad.

[Screencast from 2024-01-17 16-20-43.webm](https://github.com/VEuPathDB/web-monorepo/assets/365139/f7b4e7f1-92ea-45ce-a757-92f73c19bb30)

**Comment by moontrip** [comment]
For a record purpose, it is due to flyTo involving zoom-in that leads to hiding side panel by this task, https://github.com/VEuPathDB/web-monorepo/pull/743

**Comment by bobular** [comment]
Closing this because we have a plan to not have the side panel open by default in new analyses. See #745

**Comment by bobular** [comment]
Closing this because we have a plan to not have the side panel open by default in new analyses. See https://github.com/VEuPathDB/web-monorepo/issues/745
