### ISSUE TITLE
VDI - user datasets-  provide transfer status feedback when uploading large files

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#799]
currently in vdi ui when uploading large files (eg 50MB) the upload form greys out  and you dont know what is going on..

**Comment by dmfalke** [comment]
In order to provide progress, we will have to use `XMLHttpRequest` (aka, an `xhr` request), rather than `Fetch` request, since the latter does not report progress.

I suggest we do this as a one-off for this method.

**Comment by jernestmyers** [comment]
URLs to test in the VDI form:

[genelist-1.txt](https://github.com/VEuPathDB/web-monorepo/files/14115253/genelist-1.txt) (~200B)
[GenesByTaxon_GeneModelDump.txt](https://github.com/VEuPathDB/web-monorepo/files/14115267/GenesByTaxon_GeneModelDump.txt) (~17MB)

**Comment by jernestmyers** [comment]
NOTE: I pushed these changes directly to the `feature/vdi-client-work` branch that is associated with https://github.com/VEuPathDB/web-monorepo/pull/549
