### ISSUE TITLE
Update verbiage in share dataset modal

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#80]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/25450900/232647062-deaf7d2d-a287-42f9-a328-717500e33cdf.png">

- [x] Use sentence case for `With the following collaborators`
- [x] Use recipients consistently instead of collaborators or users -- change `With the following collaborators` to `With the following recipients`
- [x] Use recipients consistently instead of collaborators or users -- change `Share datasets with XX users` to `Grant XX Recipients Access to Dataset`
- [x] button should say dataset (singular) 
- [x] should button should be sentence case `Grant XX recipients access to dataset`? Buttons are usually title case
- [x] standard placement of icons in buttons is to the left of the text

**Comment by jernestmyers** [comment]
>  button should say dataset (singular)

A study owner can grant access to more than one study at a time. Thus, I've conditioned the noun to be plural/singular depending on the number of datasets being shared.

>  should button should be sentence case Grant XX recipients access to dataset? Buttons are usually title case

I'm going to stick with title case just for consistency.

**Comment by SAK22** [comment]
Looks good!
