### ISSUE TITLE
study_access attribute:   only request the attribute if it is defined in the model. 

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#81]
affecting all dev sites and feature site since they are eda enabled by default

related to https://github.com/VEuPathDB/service-dataset-download/issues/8 

<img width="1106" alt="Screen Shot 2023-02-20 at 8 24 07 AM" src="https://user-images.githubusercontent.com/16354313/220126694-456c8eb2-6370-4272-b633-380aad876dd2.png">

**Comment by dmfalke** [comment]
The attribute `bulk_download_url` should be optional.
