### ISSUE TITLE
Bug: Line plot y-axis range should always include zero

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#833]
It looks like we are no longer always including 0 as the default range for the y-axis? was this change intentional? Can we please bring it back to the way it was (ie, default to go through zero)? also, it seems like the radio button option for “full” (which i believe would include zero) is disabled. 

I plotted Time since LLIN distribution (x-axis) vs Malaria incidence rate per 1000 people (y-axis), & overlayed for Cluster study arm for unsubsetted LLINEUP2 data.

Note that none of these variables have annotated values for defaultDisplayRangeMin, defaultDisplayRangeMax, or	defaultBinWidth in the conversion file.

It looks like this:
<img width="682" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/c8c836f3-d3fe-4a57-9bd5-ecdef1b15d2e">

It should look like this by default (except, the radio button for "Full" y-axis should be selected, instead of having to play with a "custom" range):
<img width="674" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/61171c9b-3232-48e7-8426-73e4ba07e156">

**Comment by moontrip** [comment]
@danicahelb I looked back this, and yes, we removed 0 from the min sometime last year. 

If I remember correctly, this involves two previous tickets, which were requested by @d-callan and @bobular as follows. So some decisions need to be made among us where we will get back to the inclusion of 0 or not. Any insight, @d-callan and @bobular?

https://github.com/VEuPathDB/web-monorepo/issues/147

https://github.com/VEuPathDB/web-eda/issues/1698

**Comment by d-callan** [comment]
Tbh I don't see how either of those tickets should remove 0.. the one is about dates and explicitly states to go through 0 unless otherwise annotated. The other is about explicitly filtered variables and also states that if there are no filters the behavior shouldn't change. 

I think we agree what the behavior should be.. I'd rather we focus on why it isn't as expected.

**Comment by moontrip** [comment]
> Tbh I don't see how either of those tickets should remove 0.. the one is about dates and explicitly states to go through 0 unless otherwise annotated. The other is about explicitly filtered variables and also states that if there are no filters the behavior shouldn't change.
> 
> I think we agree what the behavior should be.. I'd rather we focus on why it isn't as expected.

Thank you for sharing your thoughts, @d-callan 👍 I further looked back our history, and found that you were correct. So, what we have decided before was that we would consider zero only if displayMin does not exist (i.e., undefined) in the variable's metadata. I tried to check LLINEUP2 data and see what the displayMin of Malaria incidence rate per 1000 people is, but I could not access the LLINEUP2 data from my dev Env. However, I guess that there exists displayMin which is larger than 0, so zero is not shown in the plot <- @danicahelb

**Comment by bobular** [comment]
Malaria incidence does not have an annotated range, it only has the calculated min and max:
```
{
	"distributionDefaults": {
		"rangeMin": 289,
		"rangeMax": 697,
		"binWidth": 58
	}
}
```

**Comment by bobular** [comment]
I'm having trouble getting a dev site to work with LLINEUP2 so I found a suitable equivalent in LLINEUP1

The Hemoglobin variable doesn't go close to zero and has no annotated display range
```
{
	"distributionDefaults": {
		"rangeMin": 1.89999997615814,
		"rangeMax": 20.2999992370605,
		"binWidth": 0.83636360277
	}
}
```

![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/b5e792c3-4218-44ce-afab-90f59279c14e)

**Comment by bobular** [comment]
Further investigations show that this may have been the case for 2 years.

Luckily there are no obvious problems with axis range calculations.

The problem is that we, for some unknown reason, decided that non-proportion (aka categorical) y-axes should be "Auto-zoom" by default and we disabled the "Full" option.

It seems a relatively simple fix is to make "Full" the default in all cases and of course no longer disabled that option.

I've put in a PR for testing.

**Comment by danicahelb** [comment]
ah, i see why we ended up here. For https://github.com/VEuPathDB/web-eda/issues/1433, we should have gone with “Custom” as the default, and the custom range should always include the origin. Max value for the custom range should be the max aggregated (ex, max mean) value, Min value for the custom range should either be 0 or — if minimum aggregated values are negative — the minimum aggregated value. 

@bobular is this possible to implement in time for b67 release?

**Comment by moontrip** [comment]
So, @danicahelb please let me clarify several things. A fix could be simple or complicated depending on situation.

1) aggregated value is the same meaning with annotated/metadata?
2) For the min value, we are respecting displayRangeMin (for full mode). In other words, if displayRangeMin does not exist at metadata, then we use 0 instead. That was the reason why Bob made a PR to switch back to Full range as default.
But your speaking sounds like we should use zero as another independent criterion to compare several min values, 
i.e., min of [ 0, displayRangeMin, rangeMin, observedMin ] Is this correct?
3) Do you want to use the above 2) criterion for both Full and Custom range?
4) Do you want to use the same criterion to other Vizs as well?

**Comment by danicahelb** [comment]
this looks great, thanks for the quick fix @bobular !
