### ISSUE TITLE
UX: eda/genomics : when browsing a categorical variable with many values, sorting should reset paging to first page

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#839]
mar 282024 sam encounters another issue with this https://epvb.slack.com/archives/CMQ8K9XRS/p1711643330714609

----------

playing with the popset-eda demo, i selected a study (see snapshot), and i get 55 samples.
https://qa.restricted.clinepidb.org/analysis/UwKE5TW

I wanted to find out what organisms in these 55 samples so i sorted to bring the non zero counts on view..  but all was greyed out 0. 
The confusion was that I was stuck on page 6 unknowingly... 
**I think  that when sorting on a column we should reset the page to 1.**

![Screen Shot 2024-02-09 at 12 52 13 PM](https://github.com/VEuPathDB/web-monorepo/assets/16354313/a40906b4-70d9-4367-9f72-2786a79b129d)

**Comment by jernestmyers** [comment]
> i think it i s bug... in wdk tables it doesnt mater that you are in a middle page, when sorting you bring the first or last page to view..

I'm not seeing this behavior in WDK either. I do recall adding logic that kicks us back to the first page when we change the rows per page to a number that would obviate the user's current page number.

Here's a screencast of live site where sorting still keeps user on the same page.
https://github.com/VEuPathDB/web-monorepo/assets/69446567/adba6553-346e-49fc-903b-06a2731d7ec6

**Comment by jernestmyers** [comment]
Per ui-infra FUT on 2/12/24:

**Issue**: Current sort with paging _**does not**_ revert user page 1. This can be a bit confusing to the user depending on the column data. At times, it's unclear if the sort actually took effect.

**Solution**: Kick user to page 1 when they sort

**Comment by bobular** [comment]
Sam noted that "keep checked at top" is technically correct because it keeps the checked item at the top of the table, but if you go to page 2 it doesn't stay there.

We could at least apply the same solution as proposed for sorting ("keep check at top" is essentially a special kind of sort) and switch to page one when the toggle is toggled.
