### ISSUE TITLE
eda viz dashboard: weird issue with missing background?

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#841]
not sure it is reproducible..
<img width="1131" alt="eda viz dashboard: weird missing background" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/bb212aa7-f1f7-40ce-841b-227363ccebb3">

**Comment by jernestmyers** [comment]
This appears to happen when we have more than one unconfigured computation for the same app and viz:
![image](https://github.com/VEuPathDB/web-monorepo/assets/69446567/8cd04bf6-de48-4fa3-ae98-c9186eb1251b)
