### ISSUE TITLE
eda: enable URL to access a study on a map (or eda workspace too?) with filters applied

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#845]
The use case is mapping the old mapveu link:
https://vectorbase.org/popbio-map/web/?projectID=VBP0000806
to something like
https://vectorbase.org/vectorbase/app/workspace/maps/DS_480c976ef9/EUPATH_0000605?POPBIO_8000215=VBP0000806

Or `f=POPBIO_8000215:VBP0000806` potentially multi-valued (allowing multiple variables)

We should probably limit this functionality to single value filters (e.g. one VBP ID) and use a different approach for multiple values (e.g. sequence IDs) --> https://github.com/VEuPathDB/web-monorepo/issues/912

Site search results should also use this mechanism.

DF's comment from Slack: 
> A question is, should these result in a saved analysis in the users history, or should it remain unsaved until the user does something with it (adds a new filter, configures a market, etc). Also, will we want to specify other things, like active marker type and variable?

**Comment by aurreco-uga** [comment]
unclear is this needed anymore since we came up with a new route to the map for legacy links

**Comment by dmfalke** [comment]
I don't think this is needed. Another similar case we have is for popset studies, but we will also be using something custom for that, since we could end up with filters that have a large number of values, exceeding limitations in GET requests
