### ISSUE TITLE
Map - rectangular marquee marker-selection with Ctrl-drag on map

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#863]
Ctrl (or Cmd for Mac) click-drag of a rectangle should select the markers within it. The rectangle does not need to remain when the mouse button has been released.

Shift-drag-rectangle should continue to do the regular Leaflet zoom.

It's probably low cost once we figure out how to do it!

**Comment by dmfalke** [comment]
How do we decide if a marker is included in the selection? Some possibilities I can think of are
1. The _marker_ is _completely_ inside the rectangle
2. The _marker_ is _partially_ inside the rectangle
3. The _geohash_ is _completely_ inside the rectangle
4. The _geohash_ is _partially_ inside the rectangle
5. The _bounding box_ is _completely_ inside the rectangle
6. The _bounding box_ is _partially_ inside the rectangle

**Comment by moontrip** [comment]
I think that geohash-based one is not a good option as it is mostly invisible unless one does mouse over on a marker. Currently I am thinking of the center of a marker as a basis.
