### ISSUE TITLE
Must have for b67: LLINEUP2 banner needed indicating no data downloads until manuscript is published

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-monorepo#875]
LLINEUP2 is going to be released in b67 under "Protected" data access restrictions with active approvals. However, the providers will not approve ANY data access requests until their manuscript has been published. 

We need to let the users know that they need to wait until the publication is out to get access to the data.

Please put a banner on:

- [ ]  (1) the download tab for LLINEUP2
- [ ]  (2) the study details tab for LLINEUP2 (perhaps just above the "Data provenance" section?

Here is the verbiage for the banner: 
`Requests to access LLINEUP2 data will not be granted until the manuscript has been published`

Once the manuscript has been published, we will:
1. approve all data access requests
2. switch the restriction level to "Controlled"

**Comment by aurreco-uga** [comment]
<img width="1264" alt="Screen Shot 2024-02-19 at 2 10 06 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/32d69d4f-d3bd-4834-b20b-a99a495a3abf">
<img width="1264" alt="Screen Shot 2024-02-19 at 2 09 37 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/bf299cbf-b98a-4fbb-b738-b7989b15b4b6">

**Comment by dmfalke** [comment]
I'm closing this, since the banner is on the live site.
