### ISSUE TITLE
SAM: Allow filters to be specified in the URL via query params

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#882]
### Background

In the news we have tons of links like:
https://vectorbase.org/popbio-map/web/?projectID=VBP0000806

**ETA more thoughts:**

We should make these urls as concise as possible, so that we don't hit browser limits on URL size. I don't think that will be an issue for the map links specifically, but there may be cases in the future when we want to define multiple values and/or filters.

### Proposal

- We will use the query parameter name `f` to define filters.
- The value of `f` will be a space-delimited list of `<filterDefinition>`s
- A filter definition will be of the form `<variableId>:<values>`.
- `<values>` can be:
  - a single categorical or range value (in the case of a range value, the value will be used as both min and max)
  - a JSON array formatted list of categorical values
  - a JSON array formatted tuple of `min` and `max` for a range

For the use case above, we would have an url that looks like this:

    https://vectorbase.org/vectorbase/app/workspace/maps/DS_480c976ef9/new?f=POPBIO_8000215:VBP0000806

Multiple filters would look like this:

    https://vectorbase.org/vectorbase/app/workspace/maps/DS_480c976ef9/new?f=POPBIO_8000215:VBP0000806+OBI_0001627:["Belize","Bolivia"]

**Comment by dmfalke** [comment]
Closing in lieu of #925
