### ISSUE TITLE
Add Map app menu items to primary website header

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#89]
We will need some menu items to link to different studies in the new Map App. We need to decide what those are.

Steve's suggestions:
```
Map: Full set of vector collections
Map: Updated Maine Tick collection
Map: Updated New York collection
```

**Comment by steve-fischer-200** [comment]
at first we will only need a single menu item for the mega-study.  do not use "MapVEu" in the menu; that is an internal name
