### ISSUE TITLE
Map - revisit/refine auto-closing behaviour of the left hand panel/menu

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#902]
It would be great if we can distinguish between user actions that should close the menu (click, pan, zoom) and automatic actions (zoom during fly-to) that shouldn't.

An annoying behaviour at the moment is that upon opening a new analysis, the user might open the menu to make a filter, but in the background, markers are being retrieved and the fly-to that happens when they arrive will close the menu.

Related to potential overhaul here: 
https://github.com/VEuPathDB/web-monorepo/issues/628

Also note that a single click on the map is no longer closing the panel.

Sub tasks

- [ ] restore old intended behaviour: single click on map -> close panel
- [ ] prevent fly-to from closing the panel (unless the user clicked on the fly-to button perhaps?)
- [ ] panel should not close if user resizes their browser window

**Comment by dmfalke** [comment]
My 2 cents: we should close the menu based on "event" (aka, via callbacks passed to various components), rather than based on changes to the app state.
