### ISSUE TITLE
eda UD download

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#914]
the attributes table is empty in all UDs.  This only affects the download table we show.

I told JB:
https://epvb.slack.com/archives/CBEA7PQDQ/p1705336716640999
JB explains in slack:  if there are too many variables to load into an Oracle table (>1000) , we do not populate it
**but it happens always...** 

is this a client bug?   if not, should we add a note why the table is empty? (for when it works)
![Screen Shot 2024-01-16 at 12 58 09 PM](https://github.com/VEuPathDB/web-monorepo/assets/16354313/11df989a-74e6-4722-b0c2-5a918c8b04ed)

**Comment by dmfalke** [comment]
this is the message we include when the preview isn't available (>1000 variables)
![image](https://github.com/VEuPathDB/web-monorepo/assets/365139/c48ac9c8-5073-4c17-aac7-c5b2b307c78b)

**Comment by aurreco-uga** [comment]
this is a backend issue the attributes table doesnt get populated..  hopefully it will be fixed in vdi
