### ISSUE TITLE
User Datasets: prevent large biom files from taking over the installer for very long time

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#915]
### Background

Large files will cause the user dataset installer to crash. We need to limit files to 10MB. We can use the [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_showing_files_size) interface to check the size of a file when a user adds one to the form. This can be done before the submit button is clicked, and we should disable submission when a file is larger than we would like.

_Note: we only want to do this for biome user datasets._

### Implementation Thoughts

- Add `maxSizeBytes` to [`FileUploadConfig`](https://github.com/VEuPathDB/web-monorepo/blob/7ab1c63c66d4f609611b70a5d7303b852388b83e/packages/libs/user-datasets/src/lib/Utils/types.ts#L92-L94)
- Set `mazSizeBytes` to `10MB` in the [biome config](https://github.com/VEuPathDB/web-monorepo/blob/3c2a91470a3e28cf5ff7ad4720f84ba6c4624faa/packages/libs/user-datasets/src/lib/Utils/upload-config.tsx#L9-L28)
- Add `maxSizeBytes` to [UploadForm.tsx](https://github.com/VEuPathDB/web-monorepo/blob/ff8d1e0e991b6d2924209aa70d7fd24ca14b6d4c/packages/libs/user-datasets/src/lib/Components/UploadForm.tsx)
- Pass the new prop in [UserDatasetNewUploadController.tsx](https://github.com/VEuPathDB/web-monorepo/blob/0352d539f21269e1ee884a68357babfcf251a669/packages/libs/user-datasets/src/lib/Controllers/UserDatasetNewUploadController.tsx)
- If `maxSizeBytes` is defined, use that to render a note near the file input in [UploadForm.tsx](https://github.com/VEuPathDB/web-monorepo/blob/ff8d1e0e991b6d2924209aa70d7fd24ca14b6d4c/packages/libs/user-datasets/src/lib/Components/UploadForm.tsx), and perform the necessary validation

---

https://epvb.slack.com/archives/GBDR4LDNC/p1709807786034249

dave says it is possible: https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_showing_files_size

**Comment by dmfalke** [comment]
This stackoverflow answer includes a solution that will alert if the file is too large, and then remove the file selection. This obviates the need to disable the form.

https://stackoverflow.com/a/49490014

**Comment by aurreco-uga** [comment]
the user requested to enable larger files and danB asked us to do so. limit now to 100MB. (for VDI)

**Comment by dmfalke** [comment]
To clarify, we want a 100MD limit for VDI?

**Comment by aurreco-uga** [comment]
yes! from slack from danB https://epvb.slack.com/archives/GBWJHR2TE/p1712586152749059
