### ISSUE TITLE
Bipartite Network: Add first clicking abilities to node

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#923]
The goal is to add a few click abilities to the node.
1. Linking out. If the node is an eigengene (gene list representative), we want to get from the node to the wdk gene list results page. If the node is an enzyme we want to get to kegg. Etc. 
2. Focus. The node we clicked on gets a thicker border and the label gets bold. This node's edges remain the same color but all other edges are colored Gray300.

The backend team will provide us with a base url via a [collections attribute](https://github.com/VEuPathDB/ApiCommonData/blob/master/Load/ontology/General/collections/collections.yaml), and we can use some part of the node id or display name (details on their way) to complete the link. 

The frontend has a few pieces to complete. Feel free to take each as a separate issue or do a few or redo the breakdown - whatever makes most sense

- [ ] For the `NodeWithLabel` component, create a little node menu that appears on click (ready to work on)
- [ ] When the node is clicked, gray out all edges except those coming from the clicked node. Add a gray "Unfocused" item in the Link Color legend. Neighbor nodes (nodes linked to the clicked node) get emphasized. (ready to work on)
- [ ] Add a "Link Out" button to this little node menu
- [ ] Incorporate the actual link into the button

I'll update this ticket as we get more information, but we could at least do the first two checkboxes for now!

Mockups live in Mbio Correlation app -> Bipartite Network 2.0. Some screenshots below! Please ignore adding to a scatterplot. That will be a separate issue.

<img width="826" alt="Screen Shot 2024-03-08 at 1 34 41 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/11710234/b6b11f19-1612-404c-8797-03fb2a937d69">
<img width="825" alt="Screen Shot 2024-03-08 at 1 35 02 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/11710234/a92b989f-271e-4cd5-b29a-104c738676b6">
<img width="835" alt="Screen Shot 2024-03-08 at 1 35 16 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/11710234/50a77bf8-e077-4233-8d97-22ba41dc6413">

**Comment by steve-fischer-200** [comment]
The "Click Nodes to see... " message has to be more prominent, and should include "Export Gene List to Search"

**Comment by dmfalke** [comment]
@asizemore I want to make an implementation suggestion. I think `BipartiteNetwork` should have a prop called something like `nodeActions: NodeAction[]`, where `NodeAction` is a React component that takes the node as a prop (and whatever other context is useful). These would be rendered in the menu you see when you click on a node. Then, the `BipartiteNetworkVisualization` component can specify these actions. We might even want to allow the client compute plugin provide additional action (we might want to have a compute spcecific to wgcna). Let me know if you want to discuss this in more detail.

**Comment by dmfalke** [comment]
_Notes from huddle w/ @dmfalke, @asizemore, and @steve-fischer-200_
---

Steve floated the idea that we allow users to "link out" to a new scatterplot based on the nodes that are selected. It would work by allowing the user to click on a node in one column, and then a node in the other column, and choosing the appropriate option from the menu for the second node clicked.

This means that we need to keep a list of "selected" nodes, and an "active" node. The plot component would take these as props, while the state would be maintained in the viz. It will also be up to the viz to implement the "semi-multi-select" logic (at most one node from a given column can be selected).

**Comment by asizemore** [comment]
https://github.com/VEuPathDB/web-monorepo/assets/11710234/87140756-d297-4ed0-ae9d-d578f4a904ec

Here's an initial attempt at mocking up the above. 

@dmfalke i like the plan. If i understand correctly, the list of "selected" nodes is capped at 2 nodes, and only one node can be active at a time. And the options for node actions would be handled in `NodeAction[]`? 

Seems like we need a style for "selected node" and one for "active node". Not that they have to be terribly different or complicated, i just want to confirm so that we can finalize those styles!

**Comment by asizemore** [comment]
Also above I've grayed out edges that are not connected to the selected or active node as part of visually creating focus on those nodes. Let me know if that becomes a challenge or if you think it wise to implement that step at a later time

**Comment by dmfalke** [comment]
@asizemore Your mockup looks great! And yes, at most two selected, and only one active.

**Comment by dmfalke** [comment]
@asizemore btw, my instinct is that the "at most one node per column" rule should be handled by the viz, not the plot component. I can envision other scenarios where we might want to allow users to selected more than one node per column, maybe to set the set of ids to some external tool. Do you agree, or is this speculative? If it's speculative, then it would be easier to just encode the "at most one node per column" in the plot component. Thoughts?

**Comment by dmfalke** [comment]
> > I can envision other scenarios where we might want to allow users to selected more than one node per column, maybe to set the set of ids to some external tool
> 
> 
> 
> I think this is very wise, and I definitely agree! Either to send to an external tool, to make into a user-derived collection, to star, to filter down to just those nodes, etc etc...

These are all pretty nice use cases! Of course, it now raises the question of how those would coexist with the scatter plot use case 😁. I think we should kick that can down the road until we know we want it.

**Comment by aurreco-uga** [comment]
UX Apr 3 2024
- unclear one needs to mouseover, and then click the box.. 
- which conflicts with the clicking on the module name to highlight the connecting edge..
steve thinks the mouseover should show the "see your gene list" box without an intermediate UI. could we try that? and maybe ignore the clicking on module name for now.. doesnt seem to be that useful..

**Comment by aurreco-uga** [comment]
could we also change the layout or  the space used by the view components on top of the network?  
the eyes have to go through lots of vertical space before getting to the modules...

<img width="1279" alt="Screenshot 2024-04-04 at 6 01 55 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/64c37182-d0ac-4ff5-8b1e-3eaac735e534">

**Comment by asizemore** [comment]
The clicking on a node to highlight it is really, really important for mbio and a very common feature of interactive network visualizations. If the genomics side would prefer to have the mouseover function only, maybe we can make the interaction part of the plugin `Options` so that each site could have their preferred interaction. Additionally, we could add "Click/hover/etc the node to {do a thing}" as the plot subtitle so that there are instructions for the user.

I agree that the spacing looks a little off, but I think there's a lot to consider before we move the legends around so I think mockups would be helpful before we dive into that adventure :) . Two things that come to mind are that sometimes the network is very, very long (dave suggested we allow the svg to scroll which is probably a good idea), and that the user needs to see the legends before they can make any sense of the network. 

With all the features proposed for this viz by mbio and genomics, new layouts, and interactions, it might be helpful to spend a few meetings going through some ideas - maybe a good topic for the Monday at 1pm slot once folks have gotten to play with it all on qa?

**Comment by dmfalke** [comment]
> With all the features proposed for this viz by mbio and genomics, new layouts, and interactions, it might be helpful to spend a few meetings going through some ideas - maybe a good topic for the Monday at 1pm slot once folks have gotten to play with it all on qa?

I'm just reading this... sorry that we didn't get to meet yesterday.

As we touched on in slack yesterday, we should make a set of mock-up with the panel idea. I don't think we need to present alternatives, since it seems that the panel idea has the most support, at the moment. I'm more than happy to help with this.
