### ISSUE TITLE
SAM: Add route component to handle redirects from legacy map

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#925]
Soon, there will be an Apache redirect for links to the old map, if query params are present. These links will be redirected to the new map, and will retain the query params.

We need to modify https://github.com/VEuPathDB/web-monorepo/blob/8f14604c562bdb10994379c54bddbfa19764507b/packages/libs/web-common/src/controllers/EdaMapController.tsx to do the following, if any query params are present:

Create a new analysis with the following properties:
- If a `projectID` query param is present, use its value to create a studyId filter (`POPBIO_8000215`)
- If other query params are present, format them into a human-readable string, and add them to the `description` of the new analysis.
- Both of these can be provided to the [`createAnalysis`](https://github.com/VEuPathDB/web-monorepo/blob/f5f1923f7b01994cb339c40cb8ccaa95b4911855/packages/libs/eda/src/lib/core/api/AnalysisClient.ts#L127) method of `AnalysisClient`.

Once the analysis has been created, redirect to the new analysis.

The **Notes** side-menu section should be open by default. It's unclear how best to implement that, since the active side-menu section is currently help in component state.

If no query params are present, then skip the steps above, and render the map as usual.

---

**Question related to the Apache redirect: do we want to have a list of known query params to prevent this from happening with non-redirected links?**

Maybe we can have the Apache redirect set the original query params as the value of a new query param, named something like `legacyMapQueryParams`.

**Comment by aurreco-uga** [comment]
FUT Mar 13 2024

https://vectorbase.org/popbio-map/web/?signposts_ss=Pathogen&view=smpl&zoom_level=3&center=23.07973176244989,3.5156250000000004&summarizeBy=Sample%20type&grid=true&shared_link=true&limitTerms=true
OR
https://vectorbase.org/popbio-map/web/?signposts_ss=Pathogen&projectID=VBP0000812&view=smpl&zoom_level=4&center=26.82407078047018,45.08789062500001&summarizeBy=Project&grid=true&shared_link=true&limitTerms=true


SYSTEMS:  https://vectorbase.org/vectorbase/app/workspace/maps/legacy-redirect-handler?signposts_ss=Pathogen&view=smpl&zoom_level=3&center=23.07973176244989,3.5156250000000004&summarizeBy=Sample%20type&grid=true&shared_link=true&limitTerms=true


CLIENT:    => https://vectorbase.org/vectorbase/app/workspace/maps/DS_480c976ef9/analysis_id



***REQUEST SYSTEMS a new URL for old MAP
https://vectorbase.org/popbio-map-internal/web
