### ISSUE TITLE
EDA (parent issue) Make plasmo and host-specific versions of the correlation apps

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#929]
Plasmo and Host are itching for the correlation apps. We've agreed to release the two we have for their wgcna eigengene data with 68.

Here's the current plan:

The compute service plugins are getting refactored, so we'll need to update the compute requests.
The data service will have a plugin specifically for genomics. That makes our frontend life easier.
We need to make a third correlation plugin that uses "eigengene" (not taxa, etc) language, and allows the user to choose 1 eigengene collection and the metadata, _or_ 1 eigengene collection and the second eigengene collection.

**Comment by aurreco-uga** [comment]
UX Apr 17 2024 feedback: please add term "WGCNA" to the Correlation option when clicking on New Visualization. (it already says eigengenes). Eventually we might need a generic and a study specific name?

![Screenshot 2024-04-17 at 12 39 37 PM](https://github.com/VEuPathDB/web-monorepo/assets/16354313/8d537fc0-aca4-4c8b-a5a5-0ebfcd1fd760)
