### ISSUE TITLE
EDA UD: offer files and do not offer table preview for download 

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#949]
fut steve March 20 2024:  JB is not generatin the needed wide table, so lets offer the files and the subse download without preview.

**Comment by dmfalke** [comment]
We need a way to tell if a study doesn't have the table. Is it possible to add a property to the eda study indicating as much? Could be populated by installer, I suppose.

**Comment by aurreco-uga** [comment]
we now UDs study_ids are EDA_UDxxxxx could that be the way to identify them>

**Comment by aurreco-uga** [comment]
the backend is now telling the client if  a dataset is a user dataset
https://github.com/VEuPathDB/EdaSubsettingService/pull/139

**Comment by aurreco-uga** [comment]
![vdi-ui-errormessage](https://github.com/VEuPathDB/web-monorepo/assets/16354313/08f3ecaf-6325-4c5f-94fc-080d13694896)

**Comment by aurreco-uga** [comment]
this got fixed UX wise but we still get the 500 in error emails....
