### ISSUE TITLE
Bubble marker react component

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/web-monorepo#95]
Create svg marker similar to donut.  Props include size and color.  In future support gradients. 

Probably don't need a magnify mode.

**Comment by d-callan** [comment]
also worth noting they scale continuously in terms of size. so well have some size bubble we know to be the largest we can make, and some size we know to be the smallest. then we can also have any size in between, if the data requires it. the data will not be binned in a manner that would let us use one size bubble for all values in a specified range.
