### ISSUE TITLE
EDA : error when selecting >1000 values 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#950]
Dan will make this error a 400 but UI should try to avoid such a request
--------------------

To reproduce, production site, vectorbase.org -> Tools -> Map beta

Filters -> Collection site -> Admin region level 2

Then click on the "check all" checkbox top left in the table.

What's happening is that the filter is going to Oracle as a massive `IN` clause. I think it has >6,000 values.

```
WITH
GAZ_00000448 as (
  SELECT a.GeographicLocation_stable_id, a.Study_stable_id
  FROM eda.attributevalue_VBP_MEGA_GeographicLocation t, eda.ancestors_VBP_MEGA_GeographicLocation a
  WHERE t.GeographicLocation_stable_id = a.GeographicLocation_stable_id
  AND attribute_stable_id = 'ENVO_00000006'
  AND string_value IN ('( - Kiribati)', '( - Saint-Martin)', '(Aguadilla - Puerto Rico)', '(Alderney - Guernsey)', '(Ararat - Armenia)', '(Arecibo - Puerto Rico)', '(Armavir - Armenia)', '(Belize - Belize)', '(Bitola - North Macedonia)', '(Canóvanas - Puerto Rico)', '(Carriacou - Grenada)', '(Castel - Guernsey)', '(Castries - Saint Lucia)', '(Cayo - Belize)', '(Central - Singapore)', '(Corozal - Belize)', '(Couva-Tabaquite-Talparo - Trinidad and Tobago)', '(East - Singapore)', '(Fajardo - Puerto Rico)', '(Grenadines - Saint Vincent and the Grenadines)', '(Guayama - Puerto Rico)', '(Guánica - Puerto Rico)' [TRUNCATED!!]
```

This is perhaps an edge case that could be solved on the client side - policing the number of checked items before sending any queries off. Or very high cardinality variables, especially ID/accession variables, could have a different filter interface.

BUT...

There is some new functionality coming along in the map where marker variable selections create "little filters". In the simplest case, if we select "Sample -> biological sex" as the marker variable, the little filter is "value IN [male, female, mixed_sex, unknown]" or whatever the values actually are.  If the user makes custom color assignments with the marker config checkbox table, the little filter would reflect that.  The little filter will be applied to the timeslider filter, and new entity counts coming in the header, hopefully for b67.

Anyway, it's a common occurrence to have the little filter be "value IN [ALL, THE, VALUES]" - which is the case that's breaking the live site at the moment.  If we could have a special filter implemented on the back end "variable HAS_SOME_VALUE" that would be great, and probably help with performance too.

**Comment by aurreco-uga** [comment]
this is a suplicate of #820 so closing
