### ISSUE TITLE
Bipartite Network: Alphabetically order nodes

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#951]
Right now the node order looks all over the place. They're not ordered by degree or alphabetically. They're probably ordered by our variableId, but that's not so helpful :) 

We'd like to order the nodes A -> Z in the columns by the variable's display name. This will improve the usability of the network by making it closer to a table so that users can find what they're looking for more quickly.

**Comment by dmfalke** [comment]
I will do this as a part of #957
