### ISSUE TITLE
qa.vb map: histogram of count of traps throws 500

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#959]
To reproduce: I filtered by species "Aedes", then made a histogram for "counts of traps".
<img width="1260" alt="Screenshot 2024-03-23 at 8 05 06 PM" src="https://github.com/VEuPathDB/Rserve/assets/16354313/93fa752a-63b7-48e1-a826-2af7b077b8a3">

Rserve error:

2024-03-24 00:04:36.464773 Determined bin width slider min, max and step values.
Error in veupathUtils::cut_width(xVP, binWidth, boundary = min(xVP)) : 
  Less than two breaks in utils-cut.R
In addition: Warning messages:
1: replacing previous import ‘veupathUtils::toJSON’ by ‘jsonlite::toJSON’ when loading ‘plot.data’ 
2: In veupathUtils::nonZeroRound(binSliderMax, avgDigits) :
  Input is already zero and cannot be rounded to a non-zero number.
3: In veupathUtils::nonZeroRound(binSliderMin, avgDigits) :
  Input is already zero and cannot be rounded to a non-zero number.
4: In veupathUtils::nonZeroRound(((binSliderMax - binSliderMin)/1000),  :
  Input is already zero and cannot be rounded to a non-zero number.

**Comment by dmfalke** [comment]
This is the request body:

```json
{
	"config": {
		"barMode": "stack",
		"binSpec": {
			"type": "binWidth",
			"value": 4
		},
		"outputEntityId": "OBI_0000659",
		"valueSpec": "count",
		"xAxisVariable": {
			"entityId": "OBI_0000659",
			"variableId": "EUPATH_0043046"
		}
	},
	"filters": [
		{
			"entityId": "EUPATH_0000609",
			"stringSet": [
				"Aedes <genus>"
			],
			"type": "stringSet",
			"variableId": "OBI_0001909"
		},
		{
			"entityId": "GAZ_00000448",
			"max": 81.14748070499664,
			"min": -58.26328705248602,
			"type": "numberRange",
			"variableId": "OBI_0001620"
		},
		{
			"entityId": "GAZ_00000448",
			"left": -170.15624999000002,
			"right": -170.15625000000003,
			"type": "longitudeRange",
			"variableId": "OBI_0001621"
		}
	],
	"studyId": "VBP_MEGA"
}
```

**Comment by dmfalke** [comment]
@d-callan why do you say this binWidth (`4`) is nonsensical?

**Comment by dmfalke** [comment]
fwiw, this is the post body without filters:

```json
{
	"config": {
		"barMode": "stack",
		"binSpec": {
			"type": "binWidth",
			"value": 4
		},
		"outputEntityId": "OBI_0000659",
		"valueSpec": "count",
		"xAxisVariable": {
			"entityId": "OBI_0000659",
			"variableId": "EUPATH_0043046"
		}
	},
	"filters": [
		{
			"entityId": "GAZ_00000448",
			"max": 81.14748070499664,
			"min": -58.26328705248602,
			"type": "numberRange",
			"variableId": "OBI_0001620"
		},
		{
			"entityId": "GAZ_00000448",
			"left": -170.15624999000002,
			"right": -170.15625000000003,
			"type": "longitudeRange",
			"variableId": "OBI_0001621"
		}
	],
	"studyId": "VBP_MEGA"
}
```

I do get a success response with this, so the filter is partly responsible for the 500.

**Comment by dmfalke** [comment]
How should the client determine the appropriate bin width size?

**Comment by bobular** [comment]
I think the idea is that it shouldn't. It should let the back end figure out an appropriate bin width

**Comment by d-callan** [comment]
It shouldn't. If you pass nothing for bin width the backend will find the default for that subset,  as well as return appropriate bin slider specs.

**Comment by dmfalke** [comment]
The same issue happens in regular eda, fwiw

![image](https://github.com/VEuPathDB/web-monorepo/assets/365139/85c8a777-2416-4960-8104-74367dd9199f)

**Comment by dmfalke** [comment]
@d-callan @bobular can one of you propose rules for when the front-end should send a bin width? It almost sounds like "never", but that seems too easy

**Comment by dmfalke** [comment]
Also, this should be a 400 response, not a 500

**Comment by d-callan** [comment]
i mean it should pass one if the user modifies the default, but by default it should only pass a bin width in the filter menu (to the distributions endpoint, rather than histogram) and never in the floaters.

and yea i know a 500 isnt ideal, but its a bit non-trivial, and there are other issues floating around the place about that.

**Comment by dmfalke** [comment]
Ok, so the default bin width for visualizations should be empty. I will make an issue in web-monorepo for this

**Comment by d-callan** [comment]
could just update the title of this one no?

**Comment by dmfalke** [comment]
I would rather close this and make a new one, for future reference
