### ISSUE TITLE
Viz component for timeline plots (updated lineplot)

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/web-monorepo#96]
As per data-viz meeting on April 19 2023, this plot will have a secondary histogram showing data coverage.

related to: https://github.com/VEuPathDB/EdaDataService/issues/259

**Comment by asizemore** [comment]
It was mentioned yesterday that we'd likely want to make this with visx. If that's the case, the following should help get us started
- [Line](https://airbnb.io/visx/xychart) 
- [Bars](https://airbnb.io/visx/bars) (for the histogram)
- [Layout multiple plots](https://ownkng.dev/thoughts/facet-line-chart)
- [Providing data](https://github.com/airbnb/visx/blob/master/packages/visx-xychart/src/providers/DataProvider.tsx) I think both the histo and line would be children of `DataProvider`.

**Comment by d-callan** [comment]
I'm not currently convinced of the relationship w the line plot, and intend to add specs to #130.
