### ISSUE TITLE
EDA study access prerelease: detecting guest and react seems based on a 500

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#960]
![Screenshot 2024-03-23 at 11 07 01 AM](https://github.com/VEuPathDB/web-monorepo/assets/16354313/565ff0a4-0e4a-4040-93c7-5c224ebd15b2)

**Comment by dmfalke** [comment]
The message in the 500 response is

> "Found no entities for study: PREVIEW_Gates_REACH_LAKANA_rct"

**Comment by dmfalke** [comment]
I don't think there is anything to do here, so closing. Feel free to reopen.

**Comment by aurreco-uga** [comment]
i think what i was trying to say is that we should not learn about study types, and how to diplay them based on 500's..
