### ISSUE TITLE
EDA/SAM histogram viz - binWidth should be empty by default

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#961]
Histogram visualizations are currently using `xAxisVariable.distributionDefaults.binWidth` for the default binWidth, but this is not correct. It should use `undefined` by default.

See https://github.com/VEuPathDB/web-monorepo/issues/959 for details.

**Comment by d-callan** [comment]
might be worth looking at line plot/ timelines as well, to be sure they arent doing similar.

**Comment by bobular** [comment]
I totally agree with letting the back end determine the binWidth etc for visualizations when the user hasn't set a binWidth explicitly. However, I found a "back door" that allows the client to send inappropriate binWidths to the back end.

VB megastudy using @moontrip's PR #964 
Zoomed out
+ floating histogram of "count of traps" - all is good.
set bin width to 10 manually - all is still good
zoom in to (or select by clicking) the central Madagascar 2428 marker:
![image](https://github.com/VEuPathDB/web-monorepo/assets/308639/1d2bdfce-042b-4d3d-b80b-a495d536094f)

The histogram request still contains the `binWidth: 10` and causes some havoc on the back end. Here are the rserve logs: @d-callan 

```
2024-03-26 21:10:35.806114 Determined bin width slider min, max and step values.
Error in veupathUtils::cut_width(xVP, binWidth, boundary = min(xVP)) : 
  Less than two breaks in utils-cut.R
In addition: Warning messages:
1: replacing previous import ‘veupathUtils::toJSON’ by ‘jsonlite::toJSON’ when loading ‘plot.data’ 
2: In veupathUtils::nonZeroRound(binSliderMax, avgDigits) :
  Input is already zero and cannot be rounded to a non-zero number.
3: In veupathUtils::nonZeroRound(binSliderMin, avgDigits) :
  Input is already zero and cannot be rounded to a non-zero number.
4: In veupathUtils::nonZeroRound(((binSliderMax - binSliderMin)/1000),  :
  Input is already zero and cannot be rounded to a non-zero number.
```

This can be reproduced in regular EDA too. (Make histogram, change bin width, then filter on country=Madagascar ; though you can only reach the regular EDA for the megastudy from the dev "react server" I think)

I'm having a think about what the client could do to mitigate this. If possible!

**Comment by d-callan** [comment]
In a case where the subset changes, what do we currently do about axes? Does the visible range persist or change w the subset? Does that change for different modes (full v auto zoom)? Id personally be ok, if the user didn't set the bin width and got one for free to do the same for a new subset. But if we choose to not do that, then at min being consistent w the axes is important. The backend won't complain about these types of bin widths if you also provide it a reasonable viewport.
