### ISSUE TITLE
map: share link: in 68 we can update what we show to a shorter link

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#976]
https://redmine.apidb.org/issues/53855

https://vectorbase.org/map/Q0PtEkm

<img width="1210" alt="Screenshot 2024-03-30 at 11 01 33 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/8437937b-8b9b-4f97-b666-4d7b79af600b">

**Comment by jernestmyers** [comment]
I've seen this issue in the past, but I'm not seeing it now. Here's a screenshot from the live site. Was it somehow resolved?
