### ISSUE TITLE
User datasets - Update verbiage of share button

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-monorepo#98]
The button is currently labeled **Share**. We want to change this to **Grant Access to Data Set** in genomics sites, and **Grant Access to Study** in clinepi and mbio sites.

Let's add a property named `shareButtonLabel` to https://github.com/VEuPathDB/web-monorepo/blob/777ad3220d423085393b02c1e52e1cb836a75ea9/packages/libs/user-datasets/src/lib/Controllers/UserDatasetRouter.tsx#L16-L26. We can set this in each site's routes file.

**Comment by danicahelb** [comment]
this is a client hack to make the `Grant access` button verbiage is configurable 
- the appropriate value (study vs dataset) is passed in from each cohort "site" (ortho, genomics, clinepi, mbio)

**Comment by danicahelb** [comment]
Frontend ticket with other styling changes to the buttons can be found here: https://github.com/VEuPathDB/EdaNewIssues/issues/621
