### ISSUE TITLE
eda:  analysis not found:  suggest to the user, if the url was shared, to request a good import url from the owner

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#980]
suggest  user to request a good import url from owner (similar verbiage to what we do in strategies.)
(users often share the wrong url).

 in analyses,  we dont need to get the import url from the owner.. we can just generate it by removing the study id and adding /import , or providing the short version:  site/analysis/ID or site/map/ID
(not sure we want to offer the import url to this user)

<img width="1264" alt="verbiage-update-suggest-request-import" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/cf5c8c8f-d8d9-4a6d-ae54-62b29823a548">

<img width="1222" alt="Screenshot 2024-04-01 at 3 37 33 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/cdf2940b-e398-46d8-bed9-db7c55b4a890">

**Comment by chowington** [comment]
It looks like this might already be implemented, based on this code: https://github.com/VEuPathDB/web-monorepo/blob/356e52091b5c2609b8419b137d39b742c872d5ee/packages/libs/eda/src/lib/core/components/AnalysisError.tsx#L33-L54

@aurreco-uga Is it just not always showing up when it should? Are there different criteria for showing the share button text than just a 403 HTTP response?

**Comment by dmfalke** [comment]
I can confirm this is working (screenshot from prod site):

![image](https://github.com/user-attachments/assets/ec87e5b7-a4af-4a65-9684-a90530bb49c4)

I wonder if this was fixed on qa, but not yet released when this issue was made.

**Comment by aurreco-uga** [comment]
this works fine, as posted by dave above, when using teh wrong url to share an analysis on a curated/public  study

**Comment by aurreco-uga** [comment]
the other 2 cases:
- analysis ID not found: "import unsuccessful 404"
- analysis ID good but you dont have access to this private study:  "import unsuccessful 403"
