### ISSUE TITLE
VDI UDs: Update download tab text for user datasets

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#989]
The download tab for user datasets says:

<img width="764" alt="Screen Shot 2023-12-05 at 6 49 07 AM" src="https://github.com/VEuPathDB/EdaNewIssues/assets/11710234/7b9a0d91-066f-4c0b-8015-7ebe2c3a0194">

Can we either
1. remove the Data Accessibility section for user datasets
2. update the text so that it says something along the lines of "This is your data. Only you and those with whom you've shared this data can download it."

**Comment by jernestmyers** [comment]
Duplicated by https://github.com/VEuPathDB/web-monorepo/issues/927

I'll reference both to be closed with the PR.
