### ISSUE TITLE
Allow user to collapse floater controls

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/web-monorepo#99]
The floater controls are big.  User wants to see the floaters over the map, without additional stuff.

Allow them to collapse the controls

**Comment by adnauseum** [comment]
Mockups to prompt discussion: https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?node-id=991-14514&t=jQrnhVfZHQn6qlAk-4

**Comment by adnauseum** [comment]
From my cursory glance, it looks like all the visualization components (BarplotVisualization.tsx, BoxplotVisualization.tsx, HistogramVisualization.tsx, LineplotVisualization.tsx, etc) could be implemented with some `<VisualizationControls>` component that takes a prop to toggle hiding.

**Comment by d-callan** [comment]
id like to know how this relates, if at all, to us adding axes controls for things like binning histograms and setting axes ranges

**Comment by chowington** [comment]
Fixed by https://github.com/VEuPathDB/web-monorepo/pull/535
